### ISSUE TITLE
AWS S3 module and other modules crash due to use of deprecated cypher syntax

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#1032]
*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

As reported on Slack at https://lyftoss.slack.com/archives/CTZUQL0KX/p1668510016495049.

I believe this is also present in cartography.intel.aws.apigateway, aws_kms_details.json, gcp_gke_basic_auth.json, aws_foreign_accounts, aws_apigateway_details.json, aws_eks_asset_exposure.json, gcp_gke_asset_exposure.json, aws_ec2_asset_exposure.json, gcp_compute_asset_inet_exposure.json.

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

Run s3 sync on cartography 0.66.1.

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/cli.py", line 557, in main
    sys.exit(CLI(default_sync, prog='cartography').main(argv))
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/cli.py", line 537, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/sync.py", line 163, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/sync.py", line 85, in run
    stage_func(neo4j_session, config)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/util.py", line 133, in timed
    return method(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 237, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 161, in _sync_multiple_accounts
    _sync_one_account(
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/intel/aws/__init__.py", line 62, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/util.py", line 133, in timed
    return method(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/intel/aws/s3.py", line 729, in sync
    load_s3_details(neo4j_session, acl_and_policy_data_iter, current_aws_account_id, update_tag)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/util.py", line 133, in timed
    return method(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/intel/aws/s3.py", line 415, in load_s3_details
    run_cleanup_job(
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/util.py", line 62, in run_cleanup_job
    GraphJob.run_from_json(
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/graph/job.py", line 114, in run_from_json
    job.run(neo4j_session)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/graph/job.py", line 58, in run
    stm.run(neo4j_session)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/graph/statement.py", line 68, in run
    self._run_iterative(session)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/graph/statement.py", line 115, in _run_iterative
    result: neo4j.Result = session.write_transaction(self._run_noniterative)
  File "/opt/homebrew/lib/python3.10/site-packages/neo4j/work/simple.py", line 434, in write_transaction
    return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/neo4j/work/simple.py", line 327, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/cartography/graph/statement.py", line 88, in _run_noniterative
    result: neo4j.Result = tx.run(self.query, self.parameters)
  File "/opt/homebrew/lib/python3.10/site-packages/neo4j/work/transaction.py", line 143, in run
    result._tx_ready_run(query, parameters)
  File "/opt/homebrew/lib/python3.10/site-packages/neo4j/work/result.py", line 70, in _tx_ready_run
    self._run(query, parameters, None, None, None, None)
  File "/opt/homebrew/lib/python3.10/site-packages/neo4j/work/result.py", line 115, in _run
    self._attach()
  File "/opt/homebrew/lib/python3.10/site-packages/neo4j/work/result.py", line 204, in _attach
    self._connection.fetch_message()
  File "/opt/homebrew/lib/python3.10/site-packages/neo4j/io/_common.py", line 187, in inner
    func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/neo4j/io/_bolt4.py", line 306, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/opt/homebrew/lib/python3.10/site-packages/neo4j/io/_common.py", line 245, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: The property existence syntax `... exists(variable.property)` is no longer supported. Please use `variable.property IS NOT NULL` instead. (line 1, column 66 (offset: 65))
"MATCH (:AWSAccount{id: $AWS_ID})-[:RESOURCE]->(s:S3Bucket) WHERE EXISTS(s.anonymous_access)"
                                                                  ^}
```

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
0.66.1
- Neo4j 4.4.14.

**Comment by achantavy** [comment]
Need more information on what version of Neo4j was being run - I'm currently unable to reproduce. See https://lyftoss.slack.com/archives/CTZUQL0KX/p1668534142513689?thread_ts=1668510016.495049&cid=CTZUQL0KX

**Comment by achantavy** [comment]
Closing this out as the above crash dump was generated on Neo4j 5.x (which has just come out and we don't support it yet) and not 4.x (which we do support).
