### ISSUE TITLE
Missing requirement "oci"

### ISSUE THREAD

**Issue by resilience-jychp** [lyft/cartography#1183]
*Description*:
> oci package is missing from setup.py requirements

*To Reproduce*:
> Launch cartography in a fresh pipenv.

*Logs*:
```
Traceback (most recent call last):
  File "/home/jeremy/.local/share/virtualenvs/cartography-ra6kuGgL/bin/cartography", line 33, in <module>
    sys.exit(load_entry_point('cartography', 'console_scripts', 'cartography')())
  File "/home/jeremy/.local/share/virtualenvs/cartography-ra6kuGgL/bin/cartography", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jeremy/Repos/cartography/cartography/cli.py", line 9, in <module>
    import cartography.sync
  File "/home/jeremy/Repos/cartography/cartography/sync.py", line 29, in <module>
    import cartography.intel.oci
  File "/home/jeremy/Repos/cartography/cartography/intel/oci/__init__.py", line 9, in <module>
    import oci
ModuleNotFoundError: No module named 'oci'
```

*Additional context*:
> - Up to date cartography (commit: [0c852d26ec32e7dedda28d260290023ea98f3b7e](https://github.com/lyft/cartography/commit/0c852d26ec32e7dedda28d260290023ea98f3b7e))
> - Python 3.8.16
> - OS: Ubuntu 22.04

**Comment by resilience-jychp** [comment]
Ok ... that was a layer 8 issue, my bad.
