### ISSUE TITLE
aws_handle_regions in util.py attempts to retry on UnauthorizedOperation errors

### ISSUE THREAD

**Issue by samuel-lindemer-h2gs** [lyft/cartography#1252]
*Title*: `aws_handle_regions` in **util.py** attempts to retry on `UnauthorizedOperation` errors

*Description*:
This function contains a list of known `ERROR_CODES` (see [here](https://github.com/lyft/cartography/blob/43e5de306133691baaa30377665e20c212998b09/cartography/util.py#L236)) which, if raised, cause Cartography to skip, rather than retry try the operation. This list should include `UnauthorizedOperation`, which can occur if, for example, the IAM user has the correct permissions but an SCP has overridden it. I didn't submit a PR for this change because, although it has the desired effect, it resulted in a new error, which I don't understand. (I'm new to this project.)

*Logs*:
```
INFO:cartography.graph.statement:Completed aws_ingest_ec2_auto_scaling_groups_cleanup statement #1
INFO:cartography.graph.statement:Completed aws_ingest_ec2_auto_scaling_groups_cleanup statement #2
INFO:cartography.graph.statement:Completed aws_ingest_ec2_auto_scaling_groups_cleanup statement #3
INFO:cartography.graph.statement:Completed aws_ingest_ec2_auto_scaling_groups_cleanup statement #4
INFO:cartography.graph.statement:Completed aws_ingest_ec2_auto_scaling_groups_cleanup statement #5
INFO:cartography.graph.statement:Completed aws_ingest_ec2_auto_scaling_groups_cleanup statement #6
INFO:cartography.graph.statement:Completed aws_ingest_ec2_auto_scaling_groups_cleanup statement #7
INFO:cartography.graph.job:Finished job aws_ingest_ec2_auto_scaling_groups_cleanup
INFO:cartography.graph.statement:Completed aws_import_ec2_launch_configurations_cleanup statement #1
INFO:cartography.graph.job:Finished job aws_import_ec2_launch_configurations_cleanup
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'ap-south-1' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'eu-north-1' in account '148147037572'.
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'eu-west-3' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'eu-west-2' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'eu-west-1' in account '148147037572'.
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'ap-northeast-3' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'ap-northeast-2' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'ap-northeast-1' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'ca-central-1' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'sa-east-1' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'ap-southeast-1' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'ap-southeast-2' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'eu-central-1' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'us-east-1' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'us-east-2' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'us-west-1' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.intel.aws.ec2.instances:Syncing EC2 instances for region 'us-west-2' in account '148147037572'.
WARNING:cartography.util:You are not authorized to perform this operation. in this region. Skipping...
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.job:Finished job EC2Reservation
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.job:Finished job EC2Instance
INFO:cartography.intel.aws.ec2.images:Syncing images for region 'ap-south-1' in account '148147037572'.
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/sync.py", line 109, in run
    stage_func(neo4j_session, config)
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/util.py", line 178, in timed
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/__init__.py", line 298, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/__init__.py", line 169, in _sync_multiple_accounts
    _sync_one_account(
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/__init__.py", line 64, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/util.py", line 178, in timed
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/ec2/images.py", line 99, in sync_ec2_images
    images_in_use = get_images_in_use(neo4j_session, region, current_aws_account_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/util.py", line 178, in timed
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/ec2/images.py", line 35, in get_images_in_use
    results = neo4j_session.run(get_images_query, AWS_ACCOUNT_ID=current_aws_account_id, Region=region)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/work/result.py", line 115, in _run
    self._attach()
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/work/result.py", line 204, in _attach
    self._connection.fetch_message()
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/io/_common.py", line 187, in inner
    func(*args, **kwargs)
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/io/_bolt4.py", line 306, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/io/_common.py", line 245, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Aggregation column contains implicit grouping expressions. For example, in 'RETURN n.a, n.a + n.b + count(*)' the aggregation expression 'n.a + n.b + count(*)' includes the implicit grouping key 'n.b'. It may be possible to rewrite the query by extracting these grouping/aggregation expressions into a preceding WITH clause. Illegal expression(s): images (line 7, column 40 (offset: 321))
"    WITH collect(DISTINCT lc.image_id)+images AS images"
                                        ^}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sam/cartography/cartography/__main__.py", line 7, in <module>
    sys.exit(cartography.cli.main())
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/cli.py", line 709, in main
    sys.exit(CLI(prog='cartography').main(argv))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/cli.py", line 690, in main
    return cartography.sync.run_with_config(self.sync, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/sync.py", line 187, in run_with_config
    return sync.run(neo4j_driver, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/sync.py", line 109, in run
    stage_func(neo4j_session, config)
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/util.py", line 178, in timed
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/__init__.py", line 298, in start_aws_ingestion
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/__init__.py", line 169, in _sync_multiple_accounts
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/__init__.py", line 64, in _sync_one_account
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/util.py", line 178, in timed
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/ec2/images.py", line 99, in sync_ec2_images
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/util.py", line 178, in timed
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/cartography-0.85.0-py3.11.egg/cartography/intel/aws/ec2/images.py", line 35, in get_images_in_use
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/work/result.py", line 115, in _run
    self._attach()
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/work/result.py", line 204, in _attach
    self._connection.fetch_message()
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/io/_common.py", line 187, in inner
    func(*args, **kwargs)
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/io/_bolt4.py", line 306, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Users/sam/.pyenv/versions/dev/lib/python3.11/site-packages/neo4j/io/_common.py", line 245, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Aggregation column contains implicit grouping expressions. For example, in 'RETURN n.a, n.a + n.b + count(*)' the aggregation expression 'n.a + n.b + count(*)' includes the implicit grouping key 'n.b'. It may be possible to rewrite the query by extracting these grouping/aggregation expressions into a preceding WITH clause. Illegal expression(s): images (line 7, column 40 (offset: 321))
"    WITH collect(DISTINCT lc.image_id)+images AS images"
                                        ^}
```

*Please complete the following information:*:
- Cartography release version or commit hash [43e5de3](https://github.com/lyft/cartography/commit/43e5de306133691baaa30377665e20c212998b09)
- Python version: 3.11.3

*Additional context*:
The error logs above are the output **after** I made the suggested change. Before, it would get stuck in a retry loop, even though the operation was not authorized. I am guessing that Cartography is attempting to perform a table operation with incomplete data as a result of the change that I made, but again, I'm new to this project.

Help very much appreciated, since we're PoCing this tool on my team this week.

**Comment by achantavy** [comment]
Hi @samuel-lindemer-h2gs - thank you for the bug report!

I think `UnauthorizedOperation` should be added to that list -- I'm happy to quickly approve a PR that adds that. cc: @ramonpetgrave64 @resilience-jychp - lemme know if this is a bad idea.

As for the other error, what version of Neo4j are you running? I'll need a bit of time to debug. In the mean time you can use the `--aws-requested-syncs` parameter (described [here](https://github.com/lyft/cartography/blob/43e5de306133691baaa30377665e20c212998b09/cartography/cli.py#L214-L220)) to include only the resources you care about if EC2Image's failures are blocking you.

**Comment by ramonpetgrave64** [comment]
@achantavy I agree that it's a desired effect, but I think maybe we should enable allow bypassing only if --aws-best-effort-mode is enabled.

**Comment by achantavy** [comment]
Are you saying that in general we should only allow bypassing if `--aws-best-effort-mode` is enabled? If so, I agree but that's a much larger change that will take longer to do while @samuel-lindemer-h2gs will be blocked. For now let's add that case to the list.

**Comment by samuel-lindemer-h2gs** [comment]
Thanks for the quick reply, guys. See PR above. I'm running arm64v8/neo4j:latest on macOS Docker, which I pulled yesterday (specifically 937a938bd2f5).

One more observation: If I add `--aws-requested-syncs` and list all of the resources _except_ `ec2:images`, it runs without errors. Hope that helps.

**Comment by ramonpetgrave64** [comment]
@samuel-lindemer-h2gs Are you using neo4j v5 or v4? We're currently not yet fully supporting v5.

**Comment by ramonpetgrave64** [comment]
@achantavy yes, and okay I approved their PR
https://github.com/lyft/cartography/pull/1257#pullrequestreview-1644815780

**Comment by achantavy** [comment]
> We're currently not yet fully supporting v5.

@ramonpetgrave64 Ah yeah good catch.

@samuel-lindemer-h2gs yeah to be safe, try 4.x. 

5.x will work for _most_ things but we don't completely support it yet. We do run our integration tests on 5.x in CI, but some things will be missed (like this function 😅 ).
