### ISSUE TITLE
github sync nonetype error when listing repo-teams

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#1334]
**Bug Template**

*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

GitHub sync crashes when listing repo-teams with a Nonetype error;

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

Not sure why this suddenly started failing.

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

Crash:
```
Traceback (most recent call last):
  File "PATH/cartography/intel/github/teams.py", line 174, in sync_github_teams
    team_repos = _get_team_repos_for_multiple_teams(teams_paginated.nodes, organization, github_url, github_api_key)
  File "PATH/cartography/util.py", line 192, in timed
    result = method(*args, **kwargs)
  File "PATH/cartography/intel/github/teams.py", line 63, in _get_team_repos_for_multiple_teams
    repo_urls = [t['url'] for t in team_repos.nodes] if team_repos.nodes else []
  File "PATH/cartography/intel/github/teams.py", line 63, in <listcomp>
    repo_urls = [t['url'] for t in team_repos.nodes] if team_repos.nodes else []
TypeError: 'NoneType' object is not subscriptable
```

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
0.93.0

**Comment by achantavy** [comment]
We fail here
https://github.com/lyft/cartography/blob/e149967cd2750c614d0cb94fced6b1e60870a5cf/cartography/intel/github/teams.py#L63

which relies on data from this graphql object:
https://github.com/lyft/cartography/blob/e149967cd2750c614d0cb94fced6b1e60870a5cf/cartography/intel/github/teams.py#L85

and that is defined here:
https://docs.github.com/en/graphql/reference/objects#repository

<img width="796" alt="image" src="https://github.com/user-attachments/assets/2a2875ae-41a6-4641-b41e-19447cf4cdd3">


The `!` indicates the field is non-nullable, so since it has returned None that means something bad has happened on the GitHub server side and it is raising an exception to give us the option to stop execution.

We _could_ add in logic to continue on despite this GitHub error, but this would cause us to lose team-to-repo mappings or team permission data in the graph. This is because something wrong happened on GitHub's end and if we don't include a team-to-repo mapping in this run, it will get cleaned up and disappear.

I think I'd prefer to continue the current behavior of failing the sync here rather than losing data when GitHub has problems. Still, there may be something wrong with our specific deployment if this problem is happening frequently enough.

cc: @heryxpc

**Comment by achantavy** [comment]
It could look something like this:
<img width="894" alt="image" src="https://github.com/user-attachments/assets/541e3190-c62f-4dec-b691-2b84b70f33a2">

but again, this would mean continuing on with data loss.

**Comment by achantavy** [comment]
Another approach: wrap it with retry + sleep. I started this in https://github.com/lyft/cartography/pull/1336/files. Will add tests when I have time but assuming my theory about GitHub API not behaving well is correct, this should help.
