### ISSUE TITLE
Kandji sync throws an exception and prints a stack trace if it is not configured

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#1353]
*Title*: *One line description*

*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

I run the cartography CLI command without specifying the Kandji sync and I get the following traceback:

```
INFO:cartography.sync:Starting sync stage 'kandji'
--- Logging error ---
Traceback (most recent call last):
  File "/Users/achantavy/.pyenv/versions/3.10.13/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/Users/achantavy/.pyenv/versions/3.10.13/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/Users/achantavy/.pyenv/versions/3.10.13/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/Users/achantavy/.pyenv/versions/3.10.13/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/achantavy/.pyenv/versions/cartography/bin/cartography", line 33, in <module>
    sys.exit(load_entry_point('cartography', 'console_scripts', 'cartography')())
  File "/Users/achantavy/oss-tmp/cartography/cartography/cli.py", line 810, in main
    sys.exit(CLI(prog='cartography').main(argv))
  File "/Users/achantavy/oss-tmp/cartography/cartography/cli.py", line 791, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/Users/achantavy/oss-tmp/cartography/cartography/sync.py", line 193, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/Users/achantavy/oss-tmp/cartography/cartography/sync.py", line 115, in run
    stage_func(neo4j_session, config)
  File "/Users/achantavy/oss-tmp/cartography/cartography/util.py", line 197, in timed
    return method(*args, **kwargs)
  File "/Users/achantavy/oss-tmp/cartography/cartography/intel/kandji/__init__.py", line 23, in start_kandji_ingestion
    logger.warning(
Message: 'Required parameter(s) missing. Skipping sync.'
Arguments: ('See docs to configure.',)
INFO:cartography.sync:Finishing sync stage 'kandji'
```

Expected behavior: instead of showing a stack trace, the Kandji sync should behave like the other modules where they gracefully say something to the effect of "not configured, skipping".

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

Run `cartography` CLI without specifying kandji configuraiton.

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
0.94.0rc1

**Comment by chandanchowdhury** [comment]
Thank you @achantavy for finding this issue, re-learned a Python "gotcha" :D
