### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by chelapa** [lyft/cartography#190]
Trying to see if this works with GCP , downloaded my cred file and exported it. tried running

cartography --neo4j-user neo4j --neo4j-password-prompt --neo4j-uri bolt://localhost:7687

but get the following error, and i am not sure but how does cartography know to goto gcp if there are no config files? curious

Python 3.6.8
Neo4j 3.5.12

```
Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.6/site-packages/neobolt/direct.py", line 829, in _connect
    s = socket(AF_INET6)
  File "/usr/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/cartography/cli.py", line 182, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.6/dist-packages/cartography/cli.py", line 162, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.6/dist-packages/cartography/sync.py", line 97, in run_with_config
    auth=neo4j_auth,
  File "/home/user1/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 116, in driver
    return Driver(uri, **config)
  File "/home/user1/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 157, in __new__
    return subclass(uri, **config)
  File "/home/user1/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 231, in __new__
    pool.release(pool.acquire())
  File "/home/user1/.local/lib/python3.6/site-packages/neobolt/direct.py", line 719, in acquire
    return self.acquire_direct(self.address)
  File "/home/user1/.local/lib/python3.6/site-packages/neobolt/direct.py", line 612, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/home/user1/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 228, in connector
    return connect(address, **dict(config, **kwargs))
  File "/home/user1/.local/lib/python3.6/site-packages/neobolt/direct.py", line 976, in connect
    raise last_error
  File "/home/user1/.local/lib/python3.6/site-packages/neobolt/direct.py", line 966, in connect
    s = _connect(resolved_address, **config)
  File "/home/user1/.local/lib/python3.6/site-packages/neobolt/direct.py", line 846, in _connect
    s.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by chelapa** [comment]
Might have been due to server not accepting anything other than 127.0.0.1 sorry!
