### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'okta_api_key'

### ISSUE THREAD

**Issue by pizza0rodeo** [lyft/cartography#202]
I've installed Cartography 0.13.0 in a Python 3.6.8 venv and am running it like so:

```
cartography --neo4j-uri bolt://localhost:7687
```

...but I get an uncaught exception when it gets to the Okta stage:

```
INFO:cartography.sync:Starting sync stage 'okta'
ERROR:cartography.sync:Unhandled exception during sync stage 'okta'
Traceback (most recent call last):
  File "/home/ec2-user/venv/lib64/python3.6/site-packages/cartography/sync.py", line 69, in run
    stage_func(neo4j_session, config)
  File "/home/ec2-user/venv/lib64/python3.6/site-packages/cartography/intel/okta/__init__.py", line 48, in start_okta_ingestion
    users.sync_okta_users(neo4j_session, config.okta_org_id, config.update_tag, config.okta_api_key, state)
AttributeError: 'Namespace' object has no attribute 'okta_api_key'
Traceback (most recent call last):
  File "/home/ec2-user/venv/bin/cartography", line 11, in <module>
    load_entry_point('cartography==0.13.0', 'console_scripts', 'cartography')()
  File "/home/ec2-user/venv/lib64/python3.6/site-packages/cartography/cli.py", line 216, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/home/ec2-user/venv/lib64/python3.6/site-packages/cartography/cli.py", line 196, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/home/ec2-user/venv/lib64/python3.6/site-packages/cartography/sync.py", line 135, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/home/ec2-user/venv/lib64/python3.6/site-packages/cartography/sync.py", line 69, in run
    stage_func(neo4j_session, config)
  File "/home/ec2-user/venv/lib64/python3.6/site-packages/cartography/intel/okta/__init__.py", line 48, in start_okta_ingestion
    users.sync_okta_users(neo4j_session, config.okta_org_id, config.update_tag, config.okta_api_key, state)
AttributeError: 'Namespace' object has no attribute 'okta_api_key'
```

I'm not using Okta, and have not provided it any of the CLI options or environment variables for Okta, but it looks as if Cartography is assuming that the `okta_api_key` attribute will be there despite that. Am I doing something wrong here?

Thanks for your help!

**Comment by achantavy** [comment]
CC: @sachafaust, @SecPrez

**Comment by achantavy** [comment]
Thank you for bringing this to our attention.  We shouldn't assume that `okta_api_key` is available on the config object if you aren't an Okta user.  I think the right solution would be to add validation here ().  In the meantime while we fix this, the hacky thing to do would be to comment out the Okta sync here https://github.com/lyft/cartography/blob/master/cartography/sync.py#L152 so it doesn't get angry.

A bit more in depth - you can also create custom syncs for yourself here: https://github.com/lyft/cartography/blob/master/docs/developer-guide.md#implementing-custom-sync-commands so that you only sync objects that you care about.

**Comment by kmcquade** [comment]
@pizza0rodeo @achantavy - I'm still hitting this issue, even in the most recent release with #204 

```
INFO:cartography.sync:Starting sync stage 'gcp'
DEBUG:cartography.intel.gcp:Error occurred calling GoogleCredentials.get_application_default().
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/cartography/intel/gcp/__init__.py", line 128, in start_gcp_ingestion
    credentials = GoogleCredentials.get_application_default()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/oauth2client/client.py", line 1271, in get_application_default
    return GoogleCredentials._get_implicit_credentials()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/oauth2client/client.py", line 1261, in _get_implicit_credentials
    raise ApplicationDefaultCredentialsError(ADC_HELP_MSG)
oauth2client.client.ApplicationDefaultCredentialsError: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
ERROR:cartography.intel.gcp:Unable to initialize Google Compute Platform creds. If you don't have GCP data or don't want to load GCP data then you can ignore this message. Otherwise, the error code is: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information. Make sure your GCP credentials are configured correctly, your credentials file (if any) is valid, and that the identity you are authenticating to has the securityReviewer role attached.
INFO:cartography.sync:Finishing sync stage 'gcp'
INFO:cartography.sync:Starting sync stage 'gsuite'
DEBUG:cartography.intel.gsuite:Error occurred calling GoogleCredentials.get_application_default().
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/cartography/intel/gsuite/__init__.py", line 61, in start_gsuite_ingestion
    credentials = GoogleCredentials.from_stream(GSUITE_CREDS)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/oauth2client/client.py", line 1299, in from_stream
    'The parameter passed to the from_stream() '
oauth2client.client.ApplicationDefaultCredentialsError: The parameter passed to the from_stream() method should point to a file.
ERROR:cartography.intel.gsuite:Unable to initialize GSuite creds. If you don't have GSuite data or don't want to load Gsuite data then you can ignore this message. Otherwise, the error code is: The parameter passed to the from_stream() method should point to a file. Make sure your GSuite credentials are configured correctly, your credentials file (if any) is valid. For more details see README
INFO:cartography.sync:Finishing sync stage 'gsuite'
INFO:cartography.sync:Starting sync stage 'crxcavator'
WARNING:cartography.intel.crxcavator:CRXcavator import is not configured - skipping this module. See docs to configure.
INFO:cartography.sync:Finishing sync stage 'crxcavator'
INFO:cartography.sync:Starting sync stage 'okta'
ERROR:cartography.sync:Unhandled exception during sync stage 'okta'
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/cartography/sync.py", line 69, in run
    stage_func(neo4j_session, config)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/cartography/intel/okta/__init__.py", line 37, in start_okta_ingestion
    if not config.okta_api_key:
AttributeError: 'Namespace' object has no attribute 'okta_api_key'
```
