### ISSUE TITLE
S3 buckets in `me-south-1` region fails with IllegalLocationConstraintException

### ISSUE THREAD

**Issue by flyinbutrs** [lyft/cartography#231]
*Title*: S3 buckets in `me-south-1` region fails with IllegalLocationConstraintException

*Description*:
Initial sync fails when scanning a bucket in `me-south-1` region

*To Reproduce*:
Create S3 bucket in `me-south-1` I suspect, but I don't have another account to test with at the moment.

*Logs*:
```
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cartography/cli.py", line 216, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.6/site-packages/cartography/cli.py", line 196, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.6/site-packages/cartography/sync.py", line 135, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.6/site-packages/cartography/sync.py", line 69, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/__init__.py", line 106, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, regions, config.update_tag, common_job_parameters)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/__init__.py", line 44, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, regions, sync_tag, common_job_parameters)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/__init__.py", line 22, in _sync_one_account
    s3.sync(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/s3.py", line 326, in sync
    load_s3_details(neo4j_session, acl_and_policy_data_iter, current_aws_account_id, aws_update_tag)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/s3.py", line 136, in load_s3_details
    for bucket, acl, policy in s3_details_iter:
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/s3.py", line 26, in get_s3_bucket_details
    acl = get_acl(bucket, client)
  File "/usr/local/lib/python3.6/site-packages/cartography/intel/aws/s3.py", line 54, in get_acl
    acl = client.get_bucket_acl(Bucket=bucket['Name'])
  File "/Users/drosenbloom/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 272, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/drosenbloom/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 576, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the GetBucketAcl operation: The me-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.
```
*Please complete the following information:*:
>  - Cartography release version: 0.15.0
>  - Python version: 3.6.6
>  - OS: OSX 10.4.6 (probably unrelated)

*Additional context*:
> Add any other context about the problem here.

**Comment by achantavy** [comment]
As discussed in #232, maybe #146 can help with this.  We will test #146 first and then see if we can repro this bug.  If the `IllegalConstraint` still happens, we'll incorporate the 'opt-in logic' of #232 into `cartography.intel.aws.sync_one_account()`. 

CC: @kunaals

**Comment by achantavy** [comment]
@anewton1980 Working on this now.

**Comment by achantavy** [comment]
Hey @marco-lancini, could the technique applied in https://github.com/lyft/cartography/pull/316 be used for this issue, or is this separate?

**Comment by marco-lancini** [comment]
Although different, if needed we could add `IllegalLocationConstraintException` to the list of error codes at https://github.com/lyft/cartography/blob/master/cartography/util.py#L69

**Comment by shabin-slr** [comment]
Still facing this issue. We have not opted-in for the me-south-1 region. So getting the below error while running cartography.

`botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the GetBucketAcl operation: The me-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.`

**Comment by achantavy** [comment]
Hi @flyinbutrs, @anewton1980 , not sure if you saw this but I think @shabin-slr was able to solve it in #470!
