### ISSUE TITLE
Sync of GCP bucket fails on label

### ISSUE THREAD

**Issue by max-unity** [lyft/cartography#255]
**Bug Template**

*Title*: *Sync of GCP bucket fails on label*

*Description*:
> The GCP sync job throws a TypeError and crashes when it attempts to sync a bucket that has a label.

*To Reproduce*:
> Create a GCP project, create a storage bucket in that project. Add a label (key/value pair) to that bucket. Attempt to sync Cartography on that project. 

*Logs*:
ERROR:cartography.sync:Unhandled exception during sync stage 'gcp'
Traceback (most recent call last):
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 878, in fix_parameters
    dehydrated, = dehydrator.dehydrate([parameters])
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 134, in dehydrate
    return tuple(map(dehydrate_, values))
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 130, in dehydrate_
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 130, in <dictcomp>
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 126, in dehydrate_
    return list(map(dehydrate_, obj))
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 132, in dehydrate_
    raise TypeError(obj)
TypeError: ('label-key', 'label-value')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/sync.py", line 70, in run
    stage_func(neo4j_session, config)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/__init__.py", line 149, in start_gcp_ingestion
    _sync_multiple_projects(neo4j_session, resources, projects, config.update_tag, common_job_parameters)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/__init__.py", line 109, in _sync_multiple_projects
    _sync_single_project(neo4j_session, resources, project_id, gcp_update_tag, common_job_parameters)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/__init__.py", line 87, in _sync_single_project
    storage.sync_gcp_buckets(neo4j_session, resources.storage, project_id, gcp_update_tag, common_job_parameters)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/storage.py", line 203, in sync_gcp_buckets
    load_gcp_buckets(neo4j_session, bucket_list, gcp_update_tag)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/storage.py", line 159, in load_gcp_buckets
    gcp_update_tag=gcp_update_tag,
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 455, in run
    supports_bytes=server.supports("bytes"))
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 881, in fix_parameters
    raise TypeError("Parameters of type {} are not supported".format(type(value).__name__))
TypeError: Parameters of type tuple are not supported
Traceback (most recent call last):
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 878, in fix_parameters
    dehydrated, = dehydrator.dehydrate([parameters])
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 134, in dehydrate
    return tuple(map(dehydrate_, values))
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 130, in dehydrate_
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 130, in <dictcomp>
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 126, in dehydrate_
    return list(map(dehydrate_, obj))
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/types/__init__.py", line 132, in dehydrate_
    raise TypeError(obj)
TypeError: ('label-key', 'label-value')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cartography", line 11, in <module>
    sys.exit(main())
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/cli.py", line 259, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/cli.py", line 239, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/sync.py", line 136, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/sync.py", line 70, in run
    stage_func(neo4j_session, config)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/__init__.py", line 149, in start_gcp_ingestion
    _sync_multiple_projects(neo4j_session, resources, projects, config.update_tag, common_job_parameters)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/__init__.py", line 109, in _sync_multiple_projects
    _sync_single_project(neo4j_session, resources, project_id, gcp_update_tag, common_job_parameters)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/__init__.py", line 87, in _sync_single_project
    storage.sync_gcp_buckets(neo4j_session, resources.storage, project_id, gcp_update_tag, common_job_parameters)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/storage.py", line 203, in sync_gcp_buckets
    load_gcp_buckets(neo4j_session, bucket_list, gcp_update_tag)
  File "/home/<username>/.local/lib/python3.6/site-packages/cartography/intel/gcp/storage.py", line 159, in load_gcp_buckets
    gcp_update_tag=gcp_update_tag,
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 455, in run
    supports_bytes=server.supports("bytes"))
  File "/home/<username>/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 881, in fix_parameters
    raise TypeError("Parameters of type {} are not supported".format(type(value).__name__))
TypeError: Parameters of type tuple are not supported

*Please complete the following information:*:
>  - Cartography release version or commit hash 0.18.0
>  - Python version: 3.6
>  - OS (feel free to omit this if you don't think it's relevant to your issue): Ubuntu 18.04

*Additional context*:
> The integration test does not capture these labels: https://github.com/lyft/cartography/blob/master/tests/integration/cartography/intel/gcp/test_storage.py#L14

**Comment by achantavy** [comment]
It looks like it's failing [here](https://github.com/lyft/cartography/blob/37ede738bd2e6e87684ccc419e3f7dd314e00111/cartography/intel/gcp/storage.py#L68) because labels are tuples and Neo4j doesn't look happy ingesting tuples.

As I mentioned in DM, the [integration test data](https://github.com/lyft/cartography/blob/4271021d618b57c6c6183c164ea6dd2f5612ffb2/tests/data/gcp/storage.py) doesn't have any labels, so that explains why [our tests](https://github.com/lyft/cartography/blob/37ede738bd2e6e87684ccc419e3f7dd314e00111/tests/integration/cartography/intel/gcp/test_storage.py#L14) haven't caught it.

Would you be willing to provide censored data for one bucket that has labels?

Then we can run our integration tests and who knows, maybe we'll discover that a certain version of Neo4j works (probably not the case tbh), and then we'd be able to represent labels correctly.

**Comment by max-unity** [comment]
Provided via DM

**Comment by achantavy** [comment]
Here we go - I have a repro.  I set sample bucket data (see [here](https://github.com/lyft/cartography/pull/256/commits/f7bad042727724490f0c975ff2fbbfee67c10459#diff-446820f91d46db96e5a8b40f80eb95b5):
```
STORAGE_RESPONSE = {
    "kind": "storage#buckets",
    "items": [
            {
                "kind": "storage#bucket",
                "id": "bucket_name",
                [... all the other usual stuff ... ]
                "labels": {
                    "label_key_1": "label_value_1",
                    "label_key_2": "label_value_2",
                },
            },
    ],
}
```
and re-ran the integration tests:
<img width="797" alt="Screen Shot 2020-03-06 at 12 29 52 PM" src="https://user-images.githubusercontent.com/46503781/76120550-965b5800-5fa6-11ea-8842-cd826949994f.png">

<img width="731" alt="Screen Shot 2020-03-06 at 12 30 24 PM" src="https://user-images.githubusercontent.com/46503781/76120570-9e1afc80-5fa6-11ea-8563-9a2b01ea6092.png">
We didn't test for label ingestion before so we never ran into this problem.

Now we just need to find a better way to represent labels.
