### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by 492917328** [lyft/cartography#286]
**Feature request template**

*Title*: *401 Client Error*

**Bug Template**

*Title*: *One line description*

*Description*:
> in these day,I configure the catorgraphy according the skips you gave，install neoj4,cartograph，and there are no problems.But when I run cartography,I test about Github ,it showed 401 Client Error

*Logs*:
> 
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cartography-0.19.2-py3.5.egg/cartography/intel/github/__init__.py", line 35, in start_github_ingestion
    auth_data['name'],
  File "/usr/local/lib/python3.5/dist-packages/cartography-0.19.2-py3.5.egg/cartography/intel/github/github.py", line 273, in sync_github
    repos_json = get_github_repos(github_api_key, github_url, organization)
  File "/usr/local/lib/python3.5/dist-packages/cartography-0.19.2-py3.5.egg/cartography/intel/github/github.py", line 87, in get_github_repos
    results = call_github_api(query, variables, token, api_url)
  File "/usr/local/lib/python3.5/dist-packages/cartography-0.19.2-py3.5.egg/cartography/intel/github/github.py", line 20, in call_github_api
    response.raise_for_status()
  File "/home/spy/.local/lib/python3.5/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/cartography", line 11, in <module>
    load_entry_point('cartography==0.19.2', 'console_scripts', 'cartography')()
  File "/usr/local/lib/python3.5/dist-packages/cartography-0.19.2-py3.5.egg/cartography/cli.py", line 259, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.5/dist-packages/cartography-0.19.2-py3.5.egg/cartography/cli.py", line 239, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.5/dist-packages/cartography-0.19.2-py3.5.egg/cartography/sync.py", line 136, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.5/dist-packages/cartography-0.19.2-py3.5.egg/cartography/sync.py", line 70, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.5/dist-packages/cartography-0.19.2-py3.5.egg/cartography/intel/github/__init__.py", line 38, in start_github_ingestion
    logger.error("Could not complete request to the GitHub API: {}", e)
Message: 'Could not complete request to the GitHub API: {}'
Arguments: (HTTPError('401 Client Error: Unauthorized for url: https://api.github.com/graphql',),)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
and my configuraioin about Github is that:
str = json.dumps({"organization":[{"token":"1c13f384f07d9cb93f19fc3bd349182ca2ae3231","url":"https://api.github.com/graphql","name":"spandry"}]})

then encode it as env named gith_var  and use it in terminal:
###  cartography --github-config-env-var gith_var
as a result,it showed 401 Client Error .......

I am a beginner and very interested in this tool, hope someone can help me,thank everyone!!

**Comment by achantavy** [comment]
@tayasteere Can you take a look?

**Comment by achantavy** [comment]
@492917328 Also if that is a real token, please revoke it and use a new one :-)

**Comment by 492917328** [comment]
@achantavy I tried to create a new one and use it but the result showed the same error.....

**Comment by tayasteere** [comment]
Can you make a successful request with your token using curl? The example from Github documentation (https://developer.github.com/v4/guides/forming-calls/#authenticating-with-graphql) is
curl -H "Authorization: bearer token" -X POST -d " \
 { \
   \"query\": \"query { viewer { login }}\" \
 } \
" https://api.github.com/graphql

**Comment by 492917328** [comment]
@tayasteere  the curl is successful,it showed me about my login name.But the error was still unsolved.Do you have any other solutions?  Thank your help！！

**Comment by tayasteere** [comment]
@492917328 Can you please provide a screenshot of the permissions for your token?

**Comment by achantavy** [comment]
Ping @492917328
