### ISSUE TITLE
Handle RDS instances without subnet groups

### ISSUE THREAD

**Issue by dgreene-r7** [lyft/cartography#34]
I'm getting an exception during data collection when a RDS instance doesn't have an attached `DBSubnetGroup`. While this is unlikely, it's possible and the error condition should probably be handled by catching a `KeyError` [here](https://github.com/lyft/cartography/blob/master/cartography/intel/aws/rds.py#L131).

**Comment by achantavy** [comment]
Good catch, thanks for letting us know!  Mind pasting the stack trace as well?

**Comment by dgreene-r7** [comment]
Sure
```
Traceback (most recent call last):
  File "/Users/dgreene/.pyenv/versions/3.6.5/bin/cartography", line 10, in <module>
    sys.exit(main())
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/cli.py", line 180, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/cli.py", line 161, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/sync.py", line 129, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/sync.py", line 63, in run
    stage_func(neo4j_session, config)
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/intel/aws/__init__.py", line 119, in start_aws_ingestion
    _sync_multiple_accounts(session, aws_accounts, regions, config.update_tag, common_job_parameters)
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/intel/aws/__init__.py", line 60, in _sync_multiple_accounts
    _sync_one_account(session, boto3_session, account_id, regions, sync_tag, common_job_parameters)
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/intel/aws/__init__.py", line 38, in _sync_one_account
    rds.sync_rds_instances(session, boto3_session, regions, account_id, sync_tag, common_job_parameters)
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/intel/aws/rds.py", line 253, in sync_rds_instances
    load_rds_instances(neo4j_session, data, region, current_aws_account_id, aws_update_tag)
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/intel/aws/rds.py", line 109, in load_rds_instances
    _attach_ec2_subnet_groups(neo4j_session, rds, region, current_aws_account_id, aws_update_tag)
  File "/Users/dgreene/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cartography/intel/aws/rds.py", line 131, in _attach_ec2_subnet_groups
    db_sng = instance['DBSubnetGroup']
KeyError: 'DBSubnetGroup'
```

**Comment by achantavy** [comment]
Gimme 1 sec to get the pre-release out to pypi..

**Comment by dgreene-r7** [comment]
Thanks for the fix!

A suggestion: you guys use dict indexing a whole bunch which is fine except you have to be careful about `KeyError`s which I seem to keep running into. I highly recommend using `dict.get` as it allows for safer access to keys that may or may not exist. 

If you're interested I can do a bunch of the legwork and open a PR.

**Comment by achantavy** [comment]
Here we go: https://pypi.org/project/cartography/0.2.3rc1/

On KeyErrors: in general our thinking is that if a dict returned doesn't have a data field we're expecting to have, we're ok with letting the sync fail because it's violated a data contract.  For example, a lot of the code directly accesses an object's ARN using `data['SomeARN']` as opposed to using `data.get('SomeARN')`.  This way the sync will fail if an important ARN does not exist.

In the case of the RDS subnet group, I made the incorrect assumption that all RDS instances should have a DBSubnetGroup, so now I'm backtracking and adding that key check :).

**Comment by dgreene-r7** [comment]
Totally understood. I was thinking from the perspective of being a user scanning infrastructure I don't own and so, unfortunately, I'm at the whims of whether my users create their infrastructure in such a way that it fulfills the contract. If they don't, cartography bombs out and I have to start scanning all of our accounts again and we have a lot of them so it takes a long time. 

My comment was more around safety when accessing nested objects that potentially create relationships between entities. If the nested object doesn't exist then the relationship doesn't exist and a safe check with an early return might be appropriate. 

Ultimately your choice and I appreciate the work you're doing regardless 😀

**Comment by achantavy** [comment]
Got it, please continue to let us know if there are other data assumptions we make that aren't correct. 🙂
