### ISSUE TITLE
Unable to get running on MacOS

### ISSUE THREAD

**Issue by heydonovan** [lyft/cartography#35]
I'm using pyenv if that helps at all:

```
$ cartography
Traceback (most recent call last):
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/bin/cartography", line 11, in <module>
    load_entry_point('cartography==0.2.2rc1', 'console_scripts', 'cartography')()
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/cartography/cli.py", line 7, in <module>
    import cartography.sync
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/cartography/sync.py", line 8, in <module>
    import cartography.intel.aws
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/cartography/intel/aws/__init__.py", line 5, in <module>
    from cartography.intel.aws import dynamodb, ec2, elasticsearch, iam, organizations, route53, s3, rds
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/cartography/intel/aws/elasticsearch.py", line 2, in <module>
    from cartography.intel.dns import ingest_dns_record_by_fqdn
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/cartography/intel/dns.py", line 2, in <module>
    import dns.resolver
ImportError: No module named resolver

$ /Users/donovanhernandez/.pyenv/versions/2.7.15/bin/pip list | grep dns
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
dnspython           1.16.0

$ cartography --neo4j-uri bolt://localhost:7687
Traceback (most recent call last):
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/bin/cartography", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.12.122 (/Users/donovanhernandez/.pyenv/versions/2.7.15/lib/python2.7/site-packages), Requirement.parse('botocore<1.13.0,>=1.12.127'), set(['boto3']))

$ pip list  | grep boto
boto3               1.9.127
botocore            1.12.122
```

**Comment by achantavy** [comment]
Can you please try with Python3?  Our fault; forgot to include that as a requirement in the Readme.

**Comment by heydonovan** [comment]
Got it working! I’ll write up some of my steps as it was a game of whac-a-mole :joy:

**Comment by achantavy** [comment]
Great, look forward to seeing your steps!
