### ISSUE TITLE
EC2 Sync crashing on 

### ISSUE THREAD

**Issue by mdrdannyr** [lyft/cartography#387]
*Title*: EC2 sync crashes whilst ingesting the network interface

*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

Cartography crashes when running EC2 sync.  Crash is caused be TypeError on the datetime object from AttachTime when running the unwind to load network interfaces. 

Looks like we have an issue with EC2 introduced here (testing with one commit before this everything works fine):

4a8a566#diff-bc45bf58c0816746081168d89a8ba498

With current master the following function causes an error:

https://github.com/lyft/cartography/blob/master/cartography/intel/aws/ec2/instances.py#L24

When ingesting the network interface, neo4j library issues a TypeError on the datetime object. This happens because on line 64, we're sending the full NetworkInterfaces instance data. Before we were just sending individual items from within NetworkInterfaces. Although the AttachTime field is never loaded, i think the fact it's part of the Unwind is creating this behaviour. 

Seems like the neo4j library can't handle the datetime object properly. 

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

Crash happens for me on every single EC2 sync. Ensure you have a DateTime object within AttachTime. 

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

```
INFO:cartography.intel.aws.ec2:Syncing EC2 for account 'XXXXX'.
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/Users/xxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/__init__.py", line 878, in fix_parameters
    dehydrated, = dehydrator.dehydrate([parameters])
  File "/Users/xxxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/types/__init__.py", line 134, in dehydrate
    return tuple(map(dehydrate_, values))
  File "/Users/xxxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/types/__init__.py", line 130, in dehydrate_
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/Users/xxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/types/__init__.py", line 130, in <dictcomp>
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/Users/xxxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/types/__init__.py", line 126, in dehydrate_
    return list(map(dehydrate_, obj))
  File "/Users/xxxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/types/__init__.py", line 130, in dehydrate_
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/Users/xxxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/types/__init__.py", line 130, in <dictcomp>
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/Users/xxxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/types/__init__.py", line 130, in dehydrate_
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/Users/xxxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/types/__init__.py", line 130, in <dictcomp>
    return {key: dehydrate_(value) for key, value in obj.items()}
  File "/Users/xxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/types/__init__.py", line 132, in dehydrate_
    raise TypeError(obj)
TypeError: 2020-06-21 09:40:47+00:00
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxx/Work/github/cartography/cartography/sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "/Users/xxxx/Work/github/cartography/cartography/util.py", line 63, in timed
    return method(*args, **kwargs)
  File "/Users/xxxx/Work/github/cartography/cartography/intel/aws/__init__.py", line 148, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, config.update_tag, common_job_parameters)
  File "/Users/xxxx/Work/github/cartography/cartography/intel/aws/__init__.py", line 96, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/Users/xxxx/Work/github/cartography/cartography/intel/aws/__init__.py", line 44, in _sync_one_account
    ec2.sync(neo4j_session, boto3_session, regions, account_id, sync_tag, common_job_parameters)
  File "/Users/xxxx/Work/github/cartography/cartography/util.py", line 63, in timed
    return method(*args, **kwargs)
  File "/Users/xxxx/Work/github/cartography/cartography/intel/aws/ec2/__init__.py", line 30, in sync
    sync_ec2_instances(neo4j_session, boto3_session, regions, account_id, sync_tag, common_job_parameters)
  File "/Users/xxxx/Work/github/cartography/cartography/util.py", line 63, in timed
    return method(*args, **kwargs)
  File "/Users/xxxx/Work/github/cartography/cartography/intel/aws/ec2/instances.py", line 229, in sync_ec2_instances
    load_ec2_instances(neo4j_session, data, region, current_aws_account_id, aws_update_tag)
  File "/Users/xxxx/Work/github/cartography/cartography/util.py", line 63, in timed
    return method(*args, **kwargs)
  File "/Users/xxx/Work/github/cartography/cartography/intel/aws/ec2/instances.py", line 213, in load_ec2_instances
    load_ec2_instance_network_interfaces(neo4j_session, instance, aws_update_tag)
  File "/Users/xxxx/Work/github/cartography/cartography/util.py", line 63, in timed
    return method(*args, **kwargs)
  File "/Users/xxxx/Work/github/cartography/cartography/intel/aws/ec2/instances.py", line 63, in load_ec2_instance_network_interfaces
    aws_update_tag=aws_update_tag,
  File "/Users/xxxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/__init__.py", line 455, in run
    supports_bytes=server.supports("bytes"))
  File "/Users/xxx/Work/github/cartography-testing/cartographyvenv/lib/python3.7/site-packages/neo4j/__init__.py", line 881, in fix_parameters
    raise TypeError("Parameters of type {} are not supported".format(type(value).__name__))
TypeError: Parameters of type datetime are not supported
```

*Please complete the following information:*:
>  - Cartography release version or commit hash: 0a1fde2
>  - Python version: 3.7.5
>  - OS: OSX 10.15.5
>  - Relevant Python Packages: neo4j==1.7.6

**Comment by achantavy** [comment]
Sounds like we'd have to do a bit of a transform step by converting `instance.interface[].AttachTime` to string before calling https://github.com/lyft/cartography/blob/88972a2b784f9c621ab847285a12d6ff02c2b26f/cartography/intel/aws/ec2/instances.py#L227.

What version of the Neo4j database (not driver) are you running?

**Comment by mdrdannyr** [comment]
Thanks @achantavy! Your prompt on the neo4j database version helped a lot. Was using an old version (3.0) and hadn't had any issues with syncs before so DB version didn't come to mind as a possible issue! Ran a test on an updated neo4j (3.5.20) and now the sync works perfectly :) 

I'll close this issue - really appreciate the help!
