### ISSUE TITLE
create index for endpoint(id) occurs twice

### ISSUE THREAD

**Issue by davidlrosenblum** [lyft/cartography#398]
*Title*: CREATE INDEX ON :Endpoint(id) occurs twice

*Description*:
While it is OK to issue this create index command multiple times in 3.x, it is not in 4.x.
Perhaps this was meant to index the ip property?
CREATE INDEX ON :Endpoint(ip)

*To Reproduce*:
> You can look at the file and search for endpoint, or you can run it against a 4.x database.

*Logs*:
> 
INFO:cartography.sync:Starting sync stage 'create-indexes'
INFO:cartography.intel.create_indexes:Creating indexes for cartography node types.
ERROR:cartography.sync:Unhandled exception during sync stage 'create-indexes'
Traceback (most recent call last):
  File "/Users/davidrosenblum/Projects/GitHub/cartography/cartography/sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "/Users/davidrosenblum/Projects/GitHub/cartography/cartography/intel/create_indexes.py", line 22, in run
    neo4j_session.run(statement)
  File "/Users/davidrosenblum/Projects/GitHub/cartography/cartenv/lib/python3.7/site-packages/neo4j/__init__.py", line 503, in run
    self._connection.fetch()
  File "/Users/davidrosenblum/Projects/GitHub/cartography/cartenv/lib/python3.7/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/Users/davidrosenblum/Projects/GitHub/cartography/cartenv/lib/python3.7/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/Users/davidrosenblum/Projects/GitHub/cartography/cartenv/lib/python3.7/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: An equivalent index already exists, 'Index( id=43, name='index_cbb5a614', type='GENERAL BTREE', schema=(:Endpoint {id}), indexProvider='native-btree-1.0' )'.
Traceback (most recent call last):
  File "/Users/davidrosenblum/Projects/GitHub/cartography/cartenv/bin/cartography", line 11, in <module>
    load_entry_point('cartography', 'console_scripts', 'cartography')()
  File "/Users/davidrosenblum/Projects/GitHub/cartography/cartography/cli.py", line 348, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/Users/davidrosenblum/Projects/GitHub/cartography/cartography/cli.py", line 328, in main

*Please complete the following information:*:
>  - Cartography release 0.26.0 (did fresh git pull on 8/26)
>  - Python version: Python 3.7.4
>  - OS MacOS 10.15.16

*Additional context*:
None

**Comment by achantavy** [comment]
Hi there, which Neo4j version are you using? We haven't been able to get cartography working on 4.x.x so I'm very interested in your experiences here.

**Comment by davidlrosenblum** [comment]
Hi - I am using Neo4j 4.1.1 .  I fixed a lot of the cypher to use $param instead of {param}.  Not complete at all.

**Comment by achantavy** [comment]
Oh neat, is that the biggest syntax change on version 4? What benefits have you seen on 4 vs 3.5?

As for the original issue, just submitted a PR; thanks for pointing this out.

**Comment by davidlrosenblum** [comment]
There were a lot of deprecations that became real in 4.x
 Functions like toInt ==> toInteger
Parameters are now $param instead of {param}

I have found it is mostly fixing function names and changing the parameter syntax.  That doesn’t mean that you can’t take advantage of other changes by profiling the cypher and changing things around to optimize based on what it says.

The doc is here https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#cypher-deprecations-additions-removals <https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#cypher-deprecations-additions-removals>


Some of the enhancements to Neo4j Enterprise 4.x :
1) Multi-database
2) File Grained Role Based Access
3) Neo4j Fabric (ability to partition your data across servers/containers)
4) Enhanced Graph Data Science Library (GDS)

For Neo4j Community Users - you will lose those things except the GDS, which is core limited (4 cores) without a subscription, same as the prior Algo Libraries.

Cheers!

David
