### ISSUE TITLE
AWS ECR crash: AttributeError on permissions issue

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#454]
*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

A permissions issue leads to an AttributeError.

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

Run ECR sync on repo your role does not have permissions.

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

```
Traceback (most recent call last):
  File "/PATH/python3.6/site-packages/cartography/intel/aws/ecr.py", line 76, in get_ecr_image_scan_findings
    'imageTag': image_tag,
  File "/PATH/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/PATH/python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the DescribeImages operation: User: arn:aws:sts::{ACCOUNT_NUMBER}:assumed-role/{ROLE_NAME}/botocore-session-{SESSION_NUNBER} is not authorized to perform: ecr:DescribeImages on resource: arn:aws:ecr:us-east-1:{ACCOUNT_NUMBER}:repository/{REPO_NAME}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/PATH/python3.6/site-packages/cartography/sync.py", line 71, in run
    stage_func(neo4j_session, config)
  ...
  File "/PATH/python3.6/site-packages/cartography/intel/aws/__init__.py", line 98, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/PATH/python3.6/site-packages/cartography/intel/aws/__init__.py", line 46, in _sync_one_account
    ecr.sync(neo4j_session, boto3_session, regions, account_id, sync_tag, common_job_parameters)
  File "/PATH/python3.6/site-packages/cartography/util.py", line 58, in timed
    result = method(*args, **kwargs)
  File "/PATH/python3.6/site-packages/cartography/intel/aws/ecr.py", line 263, in sync
    for image_vuln_data in images_with_vulns:
  File "/PATH/python3.6/site-packages/cartography/intel/aws/ecr.py", line 256, in <genexpr>
    transform_ecr_scan_finding_attributes(v)
  File "/PATH/python3.6/site-packages/cartography/intel/aws/ecr.py", line 79, in get_ecr_image_scan_findings
    except boto3_session.client.exceptions.ImageNotFoundException:
AttributeError: 'function' object has no attribute 'exceptions'
```

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]

fa85ee88c026af636fd6c5c42b6799424507a04e

**Comment by jfoote-lyft** [comment]
I believe that except line should be
    except client.exceptions.ImageNotFoundException:
instead of 
    except boto3_session.client.exceptions.ImageNotFoundException:

The client is already generated using the boto3_session.client() function
