### ISSUE TITLE
Cartography not running due to "ssl.SSLEOFError"

### ISSUE THREAD

**Issue by shabin-slr** [lyft/cartography#466]
**Bug Template**

*Title*: *Cartography not running due to "ssl.SSLEOFError"*

*Description*:
> What issue is being seen?
Cartography crashes immediately on being run, with "ssl.SSLEOFError"

*To Reproduce*:
> Run Neo4j locally using docker
 $ docker run -d --publish=7474:7474 --publish=7687:7687  --volume=$HOME/neo4j/data:/data --env=NEO4J_AUTH=none --name=neo4j_local2 neo4j:4.1.3
> Install cartography with pip from root of cloned repo
 $ pip install -e .
> run cartography from command line
 $ cartography  --neo4j-uri bolt://127.0.0.1:7687

*Logs*:
Traceback (most recent call last):
  File "/home/shabin/.local/lib/python3.8/site-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1124)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shabin/.local/bin/cartography", line 33, in <module>
    sys.exit(load_entry_point('cartography', 'console_scripts', 'cartography')())
  File "/home/shabin/KeplerWorx/Projects/KeplerWorx/zen3c/third-party/cartography/cartography/cli.py", line 348, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/home/shabin/KeplerWorx/Projects/KeplerWorx/zen3c/third-party/cartography/cartography/cli.py", line 328, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/home/shabin/KeplerWorx/Projects/KeplerWorx/zen3c/third-party/cartography/cartography/sync.py", line 107, in run_with_config
    neo4j_driver = GraphDatabase.driver(
  File "/home/shabin/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/home/shabin/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/home/shabin/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/home/shabin/.local/lib/python3.8/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/home/shabin/.local/lib/python3.8/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/home/shabin/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/home/shabin/.local/lib/python3.8/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/home/shabin/.local/lib/python3.8/site-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/home/shabin/.local/lib/python3.8/site-packages/neobolt/direct.py", line 859, in _secure
    raise error
neobolt.exceptions.SecurityError: Failed to establish secure connection to 'EOF occurred in violation of protocol (_ssl.c:1124)'

*Please complete the following information:*:
>  - Cartography release version or commit hash: 5d27118a60c42f8a24827431ee2d95cdc2189c74
>  - Python version: 3.7.4
>  - OS: Ubuntu 18.04

**Comment by achantavy** [comment]
> env=NEO4J_AUTH=none --name=neo4j_local2 neo4j:4.1.3

Hi, we don't support Neo4j 4.x right now; try 3.5.x: https://github.com/lyft/cartography/blob/master/docs/setup/install.md#cartography-installation

**Comment by shabin-slr** [comment]
Thanks @achantavy. Its running with Neo4j 3.5
