### ISSUE TITLE
Error Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists on running cartography 

### ISSUE THREAD

**Issue by Anirudh-MV** [lyft/cartography#506]
**Error Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists on running cartography **

*Description*:
Hello, I have installed neo4j and confirmed it's working. Then I run cartography using this line `cartography --neo4j-uri bolt://localhost:7687 --neo4j-user neo4j --neo4j-password-prompt`. But when running this line and providing my correct password, I get this error

```INFO:cartography.cli:Reading password for Neo4j user 'neo4j' interactively.
Password:
INFO:cartography.sync:Starting sync with update tag '1608722184'
INFO:cartography.sync:Starting sync stage 'create-indexes'
INFO:cartography.intel.create_indexes:Creating indexes for cartography node types.
ERROR:cartography.sync:Unhandled exception during sync stage 'create-indexes'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cartography/sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.8/dist-packages/cartography/intel/create_indexes.py", line 22, in run
    neo4j_session.run(statement)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(query, parameters, self._config.database, self._config.default_access_mode, self._bookmarks, **kwparameters)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_bolt4.py", line 363, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_common.py", line 179, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ClientError: {code: Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists} {message: An equivalent index already exists, 'Index( id=60, name='index_f3a83024', type='GENERAL BTREE', schema=(:GCPNicAccessConfig {id}), indexProvider='native-btree-1.0' )'.}
Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/cartography/cli.py", line 348, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.8/dist-packages/cartography/cli.py", line 328, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.8/dist-packages/cartography/sync.py", line 145, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.8/dist-packages/cartography/sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.8/dist-packages/cartography/intel/create_indexes.py", line 22, in run
    neo4j_session.run(statement)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(query, parameters, self._config.database, self._config.default_access_mode, self._bookmarks, **kwparameters)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_bolt4.py", line 363, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_common.py", line 179, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ClientError: {code: Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists} {message: An equivalent index already exists, 'Index( id=60, name='index_f3a83024', type='GENERAL BTREE', schema=(:GCPNicAccessConfig {id}), indexProvider='native-btree-1.0' )'.}
```

Due to this error, I'm not able to move further. 

I have also tried to manually delete all the indexes in the neo4j database but this didn't help and the indexes were repopulated on running cryptography command once again.

>  - Cartography release version 1.7.8
>  - Python version: 3.8.5
>  - OS : Ubuntu 20.04 LTS

**Comment by Anirudh-MV** [comment]
Issue was with neo4j version. Installed v4.1 which gave me this error

Did a clean install with neo4j v3.5.25 and it worked like a charm. 

Closing the issue
