### ISSUE TITLE
You must specify a region

### ISSUE THREAD

**Issue by sing22** [lyft/cartography#578]
*Title*: *Unhandled exception during sync stage 'aws' - You must specify a region*

*Description*:
> AWS Sync failed multiple times with 2 separate AWS accounts. Its failing and mentioning `You must specify a region` although region is mention in the config. 
`~/.aws/config`.
```
[aws-xxxx]
role_arn = arn:aws:iam::333333333:role/cartography-read-only
region = eu-west-1
output = json
credential_source = Ec2InstanceMetadata
```

Though it works if you explicitly set the AWS_DEFAULT_REGION.  
```
export AWS_DEFAULT_REGION=eu-west-1
```

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.
Do not set AWS_DEFAULT_REGION and run the sync of account other then DEFAULT.
AWS_PROFILE=aws-xxxx cartography --neo4j-uri bolt://localhost:7687
Python Version: 3.7.9
Cartography Version: 0.31.0

*Logs*:
```
WARNING:cartography.intel.aws.s3:get_bucket_policy(xxxx-xxxx-logs) failed because the bucket no longer exists
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cartography/sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 63, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 150, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, config.update_tag, common_job_parameters)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 98, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 32, in _sync_one_account
    regions = ec2.get_ec2_regions(boto3_session)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 63, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/ec2/__init__.py", line 21, in get_ec2_regions
    client = boto3_session.client('ec2')
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 87, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 154, in compute_client_args
    s3_config=s3_config,
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 220, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 303, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 33, in <module>
    sys.exit(load_entry_point('cartography==0.31.0', 'console_scripts', 'cartography')())
  File "/usr/local/lib/python3.7/site-packages/cartography/cli.py", line 348, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.7/site-packages/cartography/cli.py", line 328, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.7/site-packages/cartography/sync.py", line 145, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.7/site-packages/cartography/sync.py", line 71, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 63, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 150, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, config.update_tag, common_job_parameters)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 98, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 32, in _sync_one_account
    regions = ec2.get_ec2_regions(boto3_session)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 63, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/ec2/__init__.py", line 21, in get_ec2_regions
    client = boto3_session.client('ec2')
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 87, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 154, in compute_client_args
    s3_config=s3_config,
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 220, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 303, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```
*Please complete the following information:*:
>  - Cartography release version or commit hash:  0.31.0
>  - Python version: 3.7.9
>  - OS: Amazon Linux release 2

*Additional context*:
> Add any other context about the problem here.

**Comment by krisek** [comment]
IMHO this patch fixes it

```
diff --git a/cartography/intel/aws/__init__.py b/cartography/intel/aws/__init__.py
index cca7513..396bb95 100644
--- a/cartography/intel/aws/__init__.py
+++ b/cartography/intel/aws/__init__.py
@@ -126,7 +126,15 @@ def _sync_multiple_accounts(
     for profile_name, account_id in accounts.items():
         logger.info("Syncing AWS account with ID '%s' using configured profile '%s'.", account_id, profile_name)
         common_job_parameters["AWS_ID"] = account_id
-        boto3_session = boto3.Session(profile_name=profile_name)
+
+        boto3_session = None
+        try:
+            boto3_session = boto3.Session(profile_name=profile_name)
+        except botocore.exceptions.ProfileNotFound:
+            logger.info("profile error '%s', trying to intitialize session without explicit profile.", profile_name)
+
+        if not boto3_session:
+            boto3_session = boto3.Session()
 
         _autodiscover_accounts(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
```

I'm less lucky nowadays with pull requests... feel free to contribute.

**Comment by achantavy** [comment]
Hi @sing22, thanks for posting the crash dump. What happens if you try

```
AWS_CONFIG_FILE=/path/to/your/aws/config cartography --neo4j-uri <uri for your neo4j instance; usually bolt://localhost:7687> --aws-sync-all-profiles
```

like in step 3 [here](https://github.com/lyft/cartography/blob/master/docs/setup/install.md)?

Without the `--aws-sync-all-profiles` switch, cartography will create a "fake profile" [here](https://github.com/lyft/cartography/blob/1fa46905e8c96cd82a399d7567f8451a6052f35c/cartography/intel/aws/organizations.py#L26), and I believe this results in the NoRegionError.

Let me know what happens and we can talk about how we can improve it.

**Comment by krisek** [comment]
I was a bit low yesterday. My patch is working in my fork for quite a while, if needed I can make a PR upstream.
