### ISSUE TITLE
Unable to skip certain services when access is denied

### ISSUE THREAD

**Issue by orenbenya** [lyft/cartography#653]
Deploying this solution on one account using an IAM user.
There are no SCP restrictions, and user have all the needed permissions as the documentation suggests.

With some services the process is able to skip any access denied issues, for example:
`WARNING:cartography.util:User: arn:aws:iam::ACCOUNTID:user/IAMUSER is not authorized to perform: dynamodb:ListTables on resource: arn:aws:dynamodb:us-west-1:ACCOUNTID:table/* with an explicit deny in this region. `**Skipping**...``

But on some services it fails with an `Unhandled exception`:
`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the DescribeAutoScalingGroups operation: User: arn:aws:iam::ACCOUNTID:user/IAMUSER is not authorized to perform: autoscaling:DescribeAutoScalingGroups with an explicit deny`

Please note that there is no explicit deny on these services (via SCP).

the full exception:
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cartography/sync.py", line 73, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 64, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 207, in start_aws_ingestion
    requested_syncs,
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 145, in _sync_multiple_accounts
    aws_requested_syncs=aws_requested_syncs,  # Could be replaced later with per-account requested syncs
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 64, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/ec2/auto_scaling_groups.py", line 133, in sync_ec2_auto_scaling_groups
    data = get_ec2_auto_scaling_groups(boto3_session, region)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 64, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 80, in inner_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/ec2/auto_scaling_groups.py", line 22, in get_ec2_auto_scaling_groups
    for page in paginator.paginate():
  File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by ericlexcellent** [comment]
I'm facing the same issue - we have some SCP in place so I thought this could be related.

**Comment by ericlexcellent** [comment]
I have made the following change and it looks to work smooth:
in util.py:

def aws_handle_regions(func):
    ERROR_CODES = [
        'AccessDeniedException',
        'UnrecognizedClientException',
        'InvalidClientTokenId',
        'AuthFailure',
        **'UnauthorizedOperation',
        'AccessDenied'**
    ]


I will confirm in the following days and if ok will make a PR.

**Comment by orenbenya** [comment]
@ericlexcellent  
Sound like a good idea!,
Sadly didn't work for me..

**Comment by achantavy** [comment]
@ericlexcellent - Sounds like a helpful PR, do you know if there's a doc from AWS on this? Feel free to tag us on the PR if you need.

@marco-lancini: what do you think about adding those two strings to the exception list for `aws_handle_regions`?

**Comment by ericlexcellent** [comment]
@achantavy I haven't found any related documentation. I'm off for a few weeks but I can make the PR when I'm back. It has been running fine for a few weeks now and I have not spotted any side effect so far.

**Comment by achantavy** [comment]
@ericlexcellent  Sounds good, appreciate the help

**Comment by cribdragg3r** [comment]
Having the same issues. Pushed the patch to `uitl.py` and re-running but, this is most certainly still an issue.

**Comment by achantavy** [comment]
I realize that there may be inconsistencies when how access errors are handled in the cartography code, but depending on your scenario it might make sense to double check the permissions setup in your environment: have you read through https://github.com/lyft/cartography/blob/master/docs/setup/config/aws.md? The intended flow is to run cartography with an AWS identity that has the SecurityAudit policy on the assets you want to sync.

But yes, I agree this is a bug: we want to support the scenario where a pentester can use the tool to scan an environment and have it skip over permission problems.
