### ISSUE TITLE
Failure while ingesting SQS queues

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#677]
There seems to be an issue with the SQS module, whereas the dead letter queue triggers an (unhandled) error:

```
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cartography/sync.py", line 73, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 207, in start_aws_ingestion
    requested_syncs,
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 145, in _sync_multiple_accounts
    aws_requested_syncs=aws_requested_syncs,  # Could be replaced later with per-account requested syncs
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/sqs.py", line 150, in sync
    load_sqs_queues(neo4j_session, queue_attributes, region, current_aws_account_id, update_tag)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/sqs.py", line 96, in load_sqs_queues
    dead_letter_arn = queue.get('RedrivePolicy', {}).get('deadLetterTargetArn')
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/cartography/cli.py", line 441, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.7/site-packages/cartography/cli.py", line 421, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.7/site-packages/cartography/sync.py", line 150, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.7/site-packages/cartography/sync.py", line 73, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 207, in start_aws_ingestion
    requested_syncs,
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 145, in _sync_multiple_accounts
    aws_requested_syncs=aws_requested_syncs,  # Could be replaced later with per-account requested syncs
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/sqs.py", line 150, in sync
    load_sqs_queues(neo4j_session, queue_attributes, region, current_aws_account_id, update_tag)
  File "/usr/local/lib/python3.7/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cartography/intel/aws/sqs.py", line 96, in load_sqs_queues
    dead_letter_arn = queue.get('RedrivePolicy', {}).get('deadLetterTargetArn')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by ryan-lane** [comment]
Ugh. I wasn't able to test this directly (didn't have a dead letter queue enabled queue available for testing) and was going off the boto3 docs. I'm guessing this is a string representation of a JSON object, with those values in it. Can you verify that for me?
