### ISSUE TITLE
Failure while cleaning up EC2 Volumes

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#678]
I've been experiencing issues with the cleanup of EC2 Volumes:

```bash
ERROR:cartography.graph.job:Unhandled error while executing statement in job 'cleanup EC2 Volumes': 
The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. 
The transaction has not completed within the specified timeout (dbms.transaction.timeout). 
You may want to retry with a longer timeout.
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 73, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 202, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 139, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/volumes.py", line 77, in sync_ebs_volumes
    cleanup_volumes(neo4j_session, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/volumes.py", line 61, in cleanup_volumes
    run_cleanup_job(
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 32, in run_cleanup_job
    GraphJob.run_from_json(
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/job.py", line 95, in run_from_json
    job.run(neo4j_session)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/job.py", line 45, in run
    stm.run(neo4j_session)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/statement.py", line 50, in run
    self._run_iterative(tx)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/statement.py", line 83, in _run_iterative
    record: neo4j.Record = result.single()
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 985, in single
    records = list(self)
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 952, in records
    self._session.fetch()
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 527, in fetch
    detail_count, _ = self._connection.fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. The transaction has not completed within the specified timeout (dbms.transaction.timeout). You may want to retry with a longer timeout.
Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/cartography/cli.py", line 441, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.9/site-packages/cartography/cli.py", line 421, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 150, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 73, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 202, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 139, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/volumes.py", line 77, in sync_ebs_volumes
    cleanup_volumes(neo4j_session, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 66, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/volumes.py", line 61, in cleanup_volumes
    run_cleanup_job(
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 32, in run_cleanup_job
    GraphJob.run_from_json(
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/job.py", line 95, in run_from_json
    job.run(neo4j_session)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/job.py", line 45, in run
    stm.run(neo4j_session)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/statement.py", line 50, in run
    self._run_iterative(tx)
  File "/usr/local/lib/python3.9/site-packages/cartography/graph/statement.py", line 83, in _run_iterative
    record: neo4j.Record = result.single()
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 985, in single
    records = list(self)
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 952, in records
    self._session.fetch()
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 527, in fetch
    detail_count, _ = self._connection.fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. The transaction has not completed within the specified timeout (dbms.transaction.timeout). You may want to retry with a longer timeout.
```

**Comment by marco-lancini** [comment]
I can confirm (after multiple runs) this error is consistent and not flakey

**Comment by achantavy** [comment]
Reopening while we wait to see if this fixes the issues.

**Comment by achantavy** [comment]
@marco-lancini are you still seeing this?
