### ISSUE TITLE
Kubernetes config: Unable to read kubernetes config file if not in ~/.kube/config

### ISSUE THREAD

**Issue by NonoDS** [lyft/cartography#717]
*Description*:
> Cartography should be able to read kubernetes config file --k8s-kubeconfig.
> An exception is raised when reading kubernetes config file.

*To Reproduce*:
> Launch cartography without file ~/.kube/config  :
`cartography --k8s-kubeconfig /mydir/myk8sconfigfile`

*Logs*:
> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.6/dist-packages/cartography/util.py", line 73, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cartography/intel/kubernetes/__init__.py", line 24, in start_k8s_ingestion
    for client in get_k8s_clients(config.k8s_kubeconfig):
  File "/usr/local/lib/python3.6/dist-packages/cartography/intel/kubernetes/util.py", line 44, in get_k8s_clients
    clients.append(K8sClient(context["name"]))
  File "/usr/local/lib/python3.6/dist-packages/cartography/intel/kubernetes/util.py", line 34, in __init__
    self.core = K8CoreApiClient(self.name)
  File "/usr/local/lib/python3.6/dist-packages/cartography/intel/kubernetes/util.py", line 19, in __init__
    api_client = config.new_client_from_config(context=name)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/config/kube_config.py", line 872, in new_client_from_config
    persist_config=persist_config)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/config/kube_config.py", line 816, in load_kube_config
    persist_config=persist_config)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/config/kube_config.py", line 774, in _get_kube_config_loader
    'Invalid kube-config file. '
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.

>  - Cartography release version 0.47.1
>  - Python version: 3.6
>  - OS : ubuntu:bionic

**Comment by ryan-lane** [comment]
@NonoDS Based on the stack trace and looking through the code, it seems to be finding your kube-config, but maybe the file itself is invalid? If it didn't find the file at all, there would be a different stacktrace thrown (KubernetesContextNotFound in the utils module).

Have you tried loading it with the k8s CLI?

**Comment by NonoDS** [comment]
The file is valid. When i copy the same file in ~/.kube/config, the application can scan Kubernetes properly.
But if the file ~/.kube/config does not exists, i've gone the error.

**Comment by luis-guimaraes-exoawk** [comment]
This issue is still relevant today! The same error happens if the kubeconfig path is not in /var/container/.kube/config

**Comment by mfornasa** [comment]
I can confirm this (running version 0.137.0 in a Kubernetes pod). My workaround is doing both:

```
--k8s-kubeconfig /path/to/config
```

and

```
export KUBECONFIG=/path/to/config
```
