### ISSUE TITLE
load_ec2_instance_network_interfaces crashes with transient neo4j error

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#742]
*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

Similar to #734. The `load_ec2_instance_network_interfaces` function is failing with a transient neo4j error.

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

Run the ec2 sync with a large enough dataset, or in parallel with other running syncs (although from our experience with bigger parallel writers this might not be a great idea).

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

```
Traceback (most recent call last):
  File "/path/to/cartography/intel/aws/__init__.py", line 139, in _sync_multiple_accounts
    _sync_one_account(
  File "/path/to/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/path/to/cartography/util.py", line 68, in timed
    result = method(*args, **kwargs)
  File "/path/to/cartography/intel/aws/ec2/instances.py", line 306, in sync_ec2_instances
    load_ec2_instances(neo4j_session, data, region, current_aws_account_id, update_tag)
  File "/path/to/cartography/util.py", line 68, in timed
    result = method(*args, **kwargs)
  File "/path/to/cartography/intel/aws/ec2/instances.py", line 248, in load_ec2_instances
    load_ec2_instance_network_interfaces(neo4j_session, instance, update_tag)
  File "/path/to/cartography/util.py", line 68, in timed
    result = method(*args, **kwargs)
  File "/path/to/cartography/intel/aws/ec2/instances.py", line 64, in load_ec2_instance_network_interfaces
    neo4j_session.run(
  File "/path/to/neo4j/__init__.py", line 503, in run
    self._connection.fetch()
  File "/path/to/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/path/to/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/path/to/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: Unable to load NODE with id 8162887.
```

*Screenshots*:
> If applicable, add screenshots to help explain your problem.

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
0.51.0rc1

>  - Python version: [e.g. 3.7.4]
3.8.x

*Additional context*:
> Add any other context about the problem here.

**Comment by achantavy** [comment]
The fix is to use a managed transaction function like [this](https://github.com/lyft/cartography/pull/705) for that failing line

```
cartography/intel/aws/ec2/instances.py", line 64, in load_ec2_instance_network_interfaces
```
