### ISSUE TITLE
AWS: use transactions for resourcegroupstaggingapi load_tags()

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#778]
*Bug Template**

*Title*: *One line description*

*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

The resourcegroupstaggingapi sync is using `neo4j_session.run()` instead of a managed transaction function (which comes with auto retries) and is crashing. 

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

Run cartography on a large enough graph.

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

```
Traceback (most recent call last):
  File "/{PATH}/neo4j/io/_common.py", line 55, in _yield_messages
    buffer.receive(sock, 2)
  File "/{PATH}/neo4j/packstream.py", line 482, in receive
    n = sock.recv_into(view[self.used:end], end - self.used)
  File "/{PATH}/gevent/_socketcommon.py", line 688, in recv_into
    return self._sock.recv_into(*args)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/{PATH}/cartography/intel/aws/__init__.py", line 145, in _sync_multiple_accounts
    _sync_one_account(
  File "/{PATH}/cartography/intel/aws/__init__.py", line 72, in _sync_one_account
    RESOURCE_FUNCTIONS['resourcegroupstaggingapi'](**sync_args)
  File "/{PATH}/cartography/util.py", line 108, in timed
    result = method(*args, **kwargs)
  File "/{PATH}/cartography/intel/aws/resourcegroupstaggingapi.py", line 198, in sync
    load_tags(neo4j_session, tag_data, resource_type, region, update_tag)
  File "/{PATH}/cartography/util.py", line 108, in timed
    result = method(*args, **kwargs)
  File "/{PATH}/cartography/intel/aws/resourcegroupstaggingapi.py", line 156, in load_tags
    neo4j_session.run(
  File "/{PATH}/neo4j/work/simple.py", line 215, in run
    self._autoResult._run(
  File "/{PATH}/neo4j/work/result.py", line 114, in _run
    self._attach()
  File "/{PATH}/neo4j/work/result.py", line 203, in _attach
    self._connection.fetch_message()
  File "/{PATH}/neo4j/io/_common.py", line 167, in inner
    func(*args, **kwargs)
  File "/{PATH}/neo4j/io/_bolt3.py", line 334, in fetch_message
    details, summary_signature, summary_metadata = next(self.inbox)
  File "/{PATH}/neo4j/io/_common.py", line 81, in __next__
    tag, fields = self.pop()
  File "/{PATH}/neo4j/io/_common.py", line 75, in pop
    return next(self._messages)
  File "/{PATH}/neo4j/io/_common.py", line 72, in _yield_messages
    self.on_error(error)
  File "/{PATH}/neo4j/io/__init__.py", line 544, in _set_defunct_read
    self._set_defunct(message, error=error, silent=silent)
  File "/{PATH}/neo4j/io/__init__.py", line 580, in _set_defunct
    raise ServiceUnavailable(message) from error
neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection IPv4Address(('{ADDRESS}', 7687)) (IPv4Address(('{IP}', 7687)))
```

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
0.55.0.rc1

**Comment by ramonpetgrave64** [comment]
Fixed it #779, though we should make an effort to convert all the queries to transactions.
