### ISSUE TITLE
Cartography doesn't works Neo4j 4.4 - EOF occurred in violation of protocol (_ssl.c:1129)

### ISSUE THREAD

**Issue by filipi86** [lyft/cartography#787]
*Title*: 
*neobolt.exceptions.SecurityError: Failed to establish secure connection to 'EOF occurred in violation of protocol (_ssl.c:1129)'*

*Description*:
I'm trying to install Cartography, but I had some problems in the installation process.

*To Reproduce*:
> pip install cartography
> cartography --neo4j-uri bolt://localhost:7687  

*Logs*:
> ┌──(thor㉿research)-[~]
└─$ cartography --neo4j-uri bolt://localhost:7687                                                                                                                            1 ⨯
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/cartography/cli.py", line 464, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.9/dist-packages/cartography/cli.py", line 444, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.9/dist-packages/cartography/sync.py", line 111, in run_with_config
    neo4j_driver = GraphDatabase.driver(
  File "/usr/local/lib/python3.9/dist-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/usr/local/lib/python3.9/dist-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/usr/local/lib/python3.9/dist-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/usr/local/lib/python3.9/dist-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 859, in _secure
    raise error
neobolt.exceptions.SecurityError: Failed to establish secure connection to 'EOF occurred in violation of protocol (_ssl.c:1129)'

*Screenshots*:
> 
![image](https://user-images.githubusercontent.com/31785433/159560829-34e69249-0a28-4a71-8108-59f0c9485494.png)

*Please complete the following information:*:
>  - Cartography release version or commit hash [Latest version installed]
>  - Python version: Python 3.9.10
>  - neo4j 4.4.2
>  - Linux research 5.16.0-kali5-amd64 Debian 5.16.14-1kali1 (2022-03-15) x86_64 GNU/Linux

*Other Logs:
> ┌──(thor㉿research)-[~]
   └─$ cartography -v
DEBUG:cartography.cli:Launching cartography with CLI configuration: {'verbose': True, 'quiet': False, 'neo4j_uri': 'bolt://localhost:7687', 'neo4j_user': None, 'neo4j_password_env_var': None, 'neo4j_password_prompt': False, 'neo4j_max_connection_lifetime': 3600, 'update_tag': None, 'aws_sync_all_profiles': False, 'azure_sync_all_subscriptions': False, 'azure_sp_auth': False, 'azure_tenant_id': None, 'azure_client_id': None, 'azure_client_secret_env_var': None, 'aws_requested_syncs': None, 'crxcavator_api_base_uri': 'https://api.crxcavator.io/v1', 'crxcavator_api_key_env_var': None, 'analysis_job_directory': None, 'okta_org_id': None, 'okta_api_key_env_var': None, 'okta_saml_role_regex': '^aws\\#\\S+\\#(?{{role}}[\\w\\-]+)\\#(?{{accountid}}\\d+)$', 'github_config_env_var': None, 'digitalocean_token_env_var': None, 'permission_relationships_file': 'cartography/data/permission_relationships.yaml', 'jamf_base_uri': None, 'jamf_user': None, 'jamf_password_env_var': None, 'k8s_kubeconfig': None, 'statsd_enabled': False, 'statsd_prefix': '', 'statsd_host': '127.0.0.1', 'statsd_port': 8125, 'pagerduty_api_key_env_var': None}
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/usr/local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/cartography/cli.py", line 464, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/local/lib/python3.9/dist-packages/cartography/cli.py", line 444, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.9/dist-packages/cartography/sync.py", line 111, in run_with_config
    neo4j_driver = GraphDatabase.driver(
  File "/usr/local/lib/python3.9/dist-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/usr/local/lib/python3.9/dist-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/usr/local/lib/python3.9/dist-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/usr/local/lib/python3.9/dist-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 859, in _secure
    raise error
neobolt.exceptions.SecurityError: Failed to establish secure connection to 'EOF occurred in violation of protocol (_ssl.c:1129)'

**Comment by udsnap** [comment]
I am also facings errors while trying to use cartography with Neo4j 4.4.4 (which is the latest available at this time) . I am not trying to use secure or SSL connection , but I feel the basic problem may be same

```
cartography -v --neo4j-uri bolt://localhost:7687
DEBUG:cartography.cli:Launching cartography with CLI configuration: {'verbose': True, 'quiet': False, 'neo4j_uri': 'bolt://localhost:7687', 'neo4j_user': None, 'neo4j_password_env_var': None, 'neo4j_password_prompt': False, 'neo4j_max_connection_lifetime': 3600, 'update_tag': None, 'aws_sync_all_profiles': False, 'azure_sync_all_subscriptions': False, 'azure_sp_auth': False, 'azure_tenant_id': None, 'azure_client_id': None, 'azure_client_secret_env_var': None, 'aws_requested_syncs': None, 'crxcavator_api_base_uri': 'https://api.crxcavator.io/v1', 'crxcavator_api_key_env_var': None, 'analysis_job_directory': None, 'okta_org_id': None, 'okta_api_key_env_var': None, 'okta_saml_role_regex': '^aws\\#\\S+\\#(?{{role}}[\\w\\-]+)\\#(?{{accountid}}\\d+)$', 'github_config_env_var': None, 'digitalocean_token_env_var': None, 'permission_relationships_file': 'cartography/data/permission_relationships.yaml', 'jamf_base_uri': None, 'jamf_user': None, 'jamf_password_env_var': None, 'k8s_kubeconfig': None, 'statsd_enabled': False, 'statsd_prefix': '', 'statsd_host': '127.0.0.1', 'statsd_port': 8125, 'pagerduty_api_key_env_var': None}
DEBUG:cartography.sync:Error occurred during Neo4j connect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 831, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 111, in run_with_config
    neo4j_driver = GraphDatabase.driver(
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 962, in connect
    s = _connect(resolved_address, **config)
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 843, in _connect
    raise ServiceUnavailable("Failed to establish connection to {!r} (reason {})".format(resolved_address, error))
neobolt.exceptions.ServiceUnavailable: Failed to establish connection to ('::1', 7687, 0, 0) (reason [Errno 61] Connection refused)
ERROR:cartography.sync:Unable to connect to Neo4j using the provided URI 'bolt://localhost:7687', an error occurred: 'Failed to establish connection to ('::1', 7687, 0, 0) (reason [Errno 61] Connection refused)'. Make sure the Neo4j server is running and accessible from your network.
```

I tried the solution proposed on this page

https://community.neo4j.com/t/cant-connect-neo4j-4-0-through-bolt-api/18726/3

If I try to connect through python code directly as mentioned on the above page, I get the same error that cartography tool throws. With the `encrypted=false` option in the python code, the error goes away. Not sure how to set the `encrypted` parameter

**Comment by marco-lancini** [comment]
Hi, Cartography doesn't support Neo4j 4.x (yet).
Migration is happening here: https://github.com/lyft/cartography/pull/521
