### ISSUE TITLE
SSL error when connecting to neobolt database

### ISSUE THREAD

**Issue by Arasteus** [lyft/cartography#789]
Bug template
*Title*: *One line description*

*Description*:
Cartography should ingest the AWS data, instead I have an SSL error, output is like this : 
`Traceback (most recent call last):
  File "/home/arasteus/.local/lib/python3.9/site-packages/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arasteus/.local/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/home/arasteus/.local/lib/python3.9/site-packages/cartography/cli.py", line 464, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/home/arasteus/.local/lib/python3.9/site-packages/cartography/cli.py", line 444, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/home/arasteus/.local/lib/python3.9/site-packages/cartography/sync.py", line 111, in run_with_config
    neo4j_driver = GraphDatabase.driver(
  File "/home/arasteus/.local/lib/python3.9/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/home/arasteus/.local/lib/python3.9/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/home/arasteus/.local/lib/python3.9/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/home/arasteus/.local/lib/python3.9/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/home/arasteus/.local/lib/python3.9/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/home/arasteus/.local/lib/python3.9/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/home/arasteus/.local/lib/python3.9/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/home/arasteus/.local/lib/python3.9/site-packages/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/home/arasteus/.local/lib/python3.9/site-packages/neobolt/direct.py", line 859, in _secure
    raise error
neobolt.exceptions.SecurityError: Failed to establish secure connection to 'EOF occurred in violation of protocol (_ssl.c:1123)'
`

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

*Logs*:
> Here is the stack trace of neo4j :  
`Directories in use:
home:         /home/arasteus/Téléchargements/neo4j-community-4.3.10
config:       /home/arasteus/Téléchargements/neo4j-community-4.3.10/conf
logs:         /home/arasteus/Téléchargements/neo4j-community-4.3.10/logs
plugins:      /home/arasteus/Téléchargements/neo4j-community-4.3.10/plugins
import:       /home/arasteus/Téléchargements/neo4j-community-4.3.10/import
data:         /home/arasteus/Téléchargements/neo4j-community-4.3.10/data
certificates: /home/arasteus/Téléchargements/neo4j-community-4.3.10/certificates
licenses:     /home/arasteus/Téléchargements/neo4j-community-4.3.10/licenses
run:          /home/arasteus/Téléchargements/neo4j-community-4.3.10/run
Starting Neo4j.
2022-03-24 10:55:46.440+0000 INFO  Starting...
2022-03-24 10:55:48.571+0000 INFO  ======== Neo4j 4.3.10 ========
2022-03-24 10:55:49.914+0000 INFO  Performing postInitialization step for component 'security-users' with version 3 and status CURRENT
2022-03-24 10:55:49.914+0000 INFO  Updating the initial password in component 'security-users'
2022-03-24 10:55:50.169+0000 INFO  Bolt enabled on localhost:7687.
2022-03-24 10:55:51.344+0000 INFO  Remote interface available at http://localhost:7474/
2022-03-24 10:55:51.349+0000 INFO  Started.
`

*Please complete the following information:*:
>  - Cartography commit hash : [6bd6900](https://github.com/lyft/cartography/commit/6bd6900260d491ec35dbbe580970f67b1ffff63e)
>  - Python version: 3.9.2
>  - OS Parrot OS latest

*Additional context*:
> Thank you for your help

**Comment by ramonpetgrave64** [comment]
I see you're using the newer `neo4j-community-4.3.10`. We currently only support version 3.5, though as 3.5 will soon be EOL, in the coming months we will begin supporting 4.x.
