### ISSUE TITLE
ECS Ingestion failures

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#800]
**Description**:
ECS ingestion for one AWS account fails with `ValueError: not enough values to unpack (expected 2, got 0)`.

See full logs below.

**Logs**:

```
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 113, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 208, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 145, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 113, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ecs.py", line 539, in sync
    cluster_arns, clusters = get_ecs_clusters(boto3_session, region)
ValueError: not enough values to unpack (expected 2, got 0)
Traceback (most recent call last):
  File "/src/custom_sync.py", line 56, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/src/custom_sync.py", line 51, in main
    return cli.CLI(build_custom_sync(), prog='cartography').main(argv)
  File "/usr/local/lib/python3.9/site-packages/cartography/cli.py", line 444, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 151, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 113, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 208, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 145, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 113, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ecs.py", line 539, in sync
    cluster_arns, clusters = get_ecs_clusters(boto3_session, region)
ValueError: not enough values to unpack (expected 2, got 0)
```

Cartography release version: `0.54.0`

**Comment by ryan-lane** [comment]
Hmm. I'm not sure how that's possible. This is the function:

```
@timeit
@aws_handle_regions
def get_ecs_clusters(boto3_session: boto3.session.Session, region: str) -> Tuple[List[str], List[Dict[str, Any]]]:
    client = boto3_session.client('ecs', region_name=region)
    paginator = client.get_paginator('list_clusters')
    clusters: List[Dict[str, Any]] = []
    cluster_arns: List[str] = []
    for page in paginator.paginate():
        cluster_arns.extend(page.get('clusterArns', []))
    # TODO: also include attachment info, and make relationships between the attachements
    # and the cluster.
    includes = ['SETTINGS', 'CONFIGURATIONS']
    for i in range(0, len(cluster_arns), 100):
        cluster_arn_chunk = cluster_arns[i:i + 100]
        cluster_chunk = client.describe_clusters(clusters=cluster_arn_chunk, include=includes)
        clusters.extend(cluster_chunk.get('clusters', []))
    return (cluster_arns, clusters)
```

The only return here is a tuple with two lists, which are initialized.

Just for sanity sake I verified that even if they're both empty, it would return correctly:

```
>>> def test_ret():
...   return ([], [])
...
>>> a, b = test_ret()
>>> a
[]
>>> b
[]
```

**Comment by marco-lancini** [comment]
Hi @ryan-lane!

> I'm not sure how that's possible

That was exactly my reaction :D

**Comment by ryan-lane** [comment]
@marco-lancini I wonder if the timeit or aws_handle_regions decorators are somehow suppressing the error. Can you try it without those headers attached, to verify?

**Comment by ryan-lane** [comment]
ah. I'm pretty sure it's `aws_handle_regions`:

```
    def inner_function(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except botocore.exceptions.ClientError as e:
            # The account is not authorized to use this service in this region
            # so we can continue without raising an exception
            if e.response['Error']['Code'] in ERROR_CODES:
                logger.warning("{} in this region. Skipping...".format(e.response['Error']['Message']))
                return []
            else:
                raise
    return inner_function
```

**Comment by ryan-lane** [comment]
@achantavy @ramonpetgrave64 

so, my guess is that the action isn't allowed in the account, but the exception is being raised and it's returning a list. It's a bit annoying that it changes the return type, especially since it makes the type checking invalid :(

**Comment by marco-lancini** [comment]
I agree.

At the time that decorator was introduced, 
the idea was to wrap `get_xxx` functions that are making atomic calls for specific resources.

In the case of `get_ecs_clusters`, instead, we are not only fetching data (`client.get_paginator('list_clusters')`) but also enriching it with data coming from other API calls  (`client.describe_clusters(...)`).

**Comment by ramonpetgrave64** [comment]
@marco-lancini @ryan-lane 
We can modify aws_handle_regions() a bit deeper to customize the return value at decoration-time. Here's an example

```
In [1]: from functools import wraps
   ...: 
   ...: 
   ...: def handle(on_error_return=None):
   ...:     def outer(func):
   ...:         ERROR_CODES = [
   ...:             ZeroDivisionError
   ...:         ]
   ...:         @wraps(func)
   ...:         def inner(*args, **kwargs):
   ...:             try:
   ...:                 return func(*args, **kwargs)
   ...:             except Exception as e:
   ...:                 if type(e) in ERROR_CODES:
   ...:                     print(f'supported error encountered {e}')
   ...:                     return on_error_return
   ...:                 else:
   ...:                     raise
   ...:         return inner
   ...:     return outer
   ...: 
   ...: @handle(on_error_return='my_default')
   ...: def f(x):
   ...:     return x/0
   ...: 
   ...: @handle(on_error_return=([], []))
   ...: def g():
   ...:     1/0
   ...: 

In [2]: f(2)
supported error encountered division by zero
Out[2]: 'my_default'

In [3]: g()
supported error encountered division by zero
Out[3]: ([], [])
```

**Comment by ramonpetgrave64** [comment]
a nicer version here that doesn't require us to change the decorator invocation elsewhere
```
In [1]: from functools import wraps
   ...: 
   ...: def handle(*args, on_error_return=[]):
   ...:     def outer(func):
   ...:         ERROR_CODES = [
   ...:             ZeroDivisionError
   ...:         ]
   ...:         @wraps(func)
   ...:         def inner(*args, **kwargs):
   ...:             try:
   ...:                 return func(*args, **kwargs)
   ...:             except Exception as e:
   ...:                 if type(e) in ERROR_CODES:
   ...:                     print(f'supported error encountered {e}')
   ...:                     return on_error_return
   ...:                 else:
   ...:                     raise
   ...:         return inner
   ...: 
   ...:     if len(args) == 1 and callable(args[0]):
   ...:         func = args[0]
   ...:         return outer(func)
   ...:     return outer
   ...: 
   ...: @handle
   ...: def k():
   ...:     return 1/0
   ...: 
   ...: @handle(on_error_return=([], []))
   ...: def g():
   ...:     1/0
   ...: 

In [2]: k()
supported error encountered division by zero
Out[2]: []

In [3]: g()
supported error encountered division by zero
Out[3]: ([], [])
```

**Comment by ryan-lane** [comment]
Ah, yeah, that solution looks good!

**Comment by ramonpetgrave64** [comment]
> Ah, yeah, that solution looks good!

Thanks!
