### ISSUE TITLE
Error while ingesting elastic_ip_addresses

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#808]
`neobolt.exceptions.ClientError: Cannot merge node using null property value for id` is triggered while trying to ingest Elastic IPs, even if none were found

*Logs*:

```
INFO:cartography.intel.aws.ec2.elastic_ip_addresses:Loading 0 Elastic IP Addresses in ca-central-1.
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 114, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 220, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 157, in _sync_multiple_accounts
    _sync_one_account(
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 60, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 114, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/elastic_ip_addresses.py", line 99, in sync_elastic_ip_addresses
    load_elastic_ip_addresses(neo4j_session, addresses, region, current_aws_account_id, update_tag)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 114, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/ec2/elastic_ip_addresses.py", line 73, in load_elastic_ip_addresses
    neo4j_session.run(
  File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 503, in run
    self._connection.fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: Cannot merge node using null property value for id
```

Cartography release version: 0.54.0

**Comment by b-milescu** [comment]
I can confirm, I have the same issue.

**Comment by ramonpetgrave64** [comment]
It seems like elastic ips don't necessarily all have allocations ids, looking at the boto response documentation.
https://boto3.amazonaws.com/v1/documentation/api/1.9.42/reference/services/ec2.html#EC2.Client.describe_addresses

But since elastic ips are meant to be public ip addresses, which should be unique, maybe the `PublicIP` is a better value for the node's `id`.

**Comment by ramonpetgrave64** [comment]
> I agree, what about #824 ?

Looks good, but one comment about updating the schema.
