### ISSUE TITLE
Error while ingesting GCP forwarding rules

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#809]
*Logs*:
```
INFO:cartography.graph.job:Finished job gcp_compute_forwarding_rules_cleanup
ERROR:cartography.sync:Unhandled exception during sync stage 'gcp'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 114, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/__init__.py", line 250, in start_gcp_ingestion
    _sync_multiple_projects(neo4j_session, resources, projects, config.update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/__init__.py", line 208, in _sync_multiple_projects
    _sync_single_project(neo4j_session, resources, project_id, gcp_update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/__init__.py", line 177, in _sync_single_project
    compute.sync(neo4j_session, resources.compute, project_id, gcp_update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/compute.py", line 1237, in sync
    sync_gcp_forwarding_rules(neo4j_session, compute, project_id, regions, gcp_update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 114, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/compute.py", line 1171, in sync_gcp_forwarding_rules
    forwarding_rules = transform_gcp_forwarding_rules(fwd_response)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 114, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/compute.py", line 331, in transform_gcp_forwarding_rules
    forwarding_rule['ip_protocol'] = fwd['IPProtocol']
KeyError: 'IPProtocol'
```

Cartography release version: 0.54.0

**Comment by ramonpetgrave64** [comment]
It seems like this value should not be empty. But I know google apis can be strange sometimes.
https://cloud.google.com/compute/docs/reference/rest/v1/forwardingRules/list

**Comment by marco-lancini** [comment]
It seems this persists with other fields:

```
ERROR:cartography.sync:Unhandled exception during sync stage 'gcp'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 115, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/__init__.py", line 250, in start_gcp_ingestion
    _sync_multiple_projects(neo4j_session, resources, projects, config.update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/__init__.py", line 208, in _sync_multiple_projects
    _sync_single_project(neo4j_session, resources, project_id, gcp_update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/__init__.py", line 177, in _sync_single_project
    compute.sync(neo4j_session, resources.compute, project_id, gcp_update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/compute.py", line 1237, in sync
    sync_gcp_forwarding_rules(neo4j_session, compute, project_id, regions, gcp_update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 115, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/compute.py", line 1171, in sync_gcp_forwarding_rules
    forwarding_rules = transform_gcp_forwarding_rules(fwd_response)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 115, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/compute.py", line 334, in transform_gcp_forwarding_rules
    forwarding_rule['load_balancing_scheme'] = fwd['loadBalancingScheme']
KeyError: 'loadBalancingScheme'
Traceback (most recent call last):
  File "/src/custom_sync.py", line 56, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/src/custom_sync.py", line 51, in main
    return cli.CLI(build_custom_sync(), prog='cartography').main(argv)
  File "/usr/local/lib/python3.9/site-packages/cartography/cli.py", line 444, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 151, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 115, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/__init__.py", line 250, in start_gcp_ingestion
    _sync_multiple_projects(neo4j_session, resources, projects, config.update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/__init__.py", line 208, in _sync_multiple_projects
    _sync_single_project(neo4j_session, resources, project_id, gcp_update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/__init__.py", line 177, in _sync_single_project
    compute.sync(neo4j_session, resources.compute, project_id, gcp_update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/compute.py", line 1237, in sync
    sync_gcp_forwarding_rules(neo4j_session, compute, project_id, regions, gcp_update_tag, common_job_parameters)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 115, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/compute.py", line 1171, in sync_gcp_forwarding_rules
    forwarding_rules = transform_gcp_forwarding_rules(fwd_response)
  File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 115, in timed
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cartography/intel/gcp/compute.py", line 334, in transform_gcp_forwarding_rules
    forwarding_rule['load_balancing_scheme'] = fwd['loadBalancingScheme']
KeyError: 'loadBalancingScheme'
```
