### ISSUE TITLE
ServiceUnavailable exception in github repo sync

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#814]
*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

ServiceUnavailable exception in github repo sync. This is weird because it will always fail the first time we try to run it and then succeed the second time.

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

```
Traceback (most recent call last):
  File "{PATH}/cartography/sync.py", line 151, in run_with_config
    return sync.run(neo4j_driver, config)
  File "{PATH}/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "{PATH}/cartography/util.py", line 112, in timed
    result = method(*args, **kwargs)
  File "{PATH}/cartography/intel/github/repos.py", line 510, in load
    load_github_repos(neo4j_session, common_job_parameters['UPDATE_TAG'], repo_data['repos'])
  File "{PATH}/cartography/util.py", line 112, in timed
    result = method(*args, **kwargs)
  File "{PATH}/cartography/intel/github/repos.py", line 409, in load_github_repos
    neo4j_session.run(
  File "{PATH}/neo4j/__init__.py", line 502, in run
    self._connection.send()
  File "{PATH}/neobolt/direct.py", line 388, in send
    self._send()
  File "{PATH}/neobolt/direct.py", line 412, in _send
    raise self.Error("Failed to write to defunct connection "
neobolt.exceptions.ServiceUnavailable: Failed to write to defunct connection Address(host='{HOSTNAME}', port=7687) (Address(host='{IP}', port=7687))
```

*Screenshots*:
> If applicable, add screenshots to help explain your problem.

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
0.57.0rc1.

**Comment by achantavy** [comment]
Closing since this hasn't been repro'd recently and has had no activity. Will reopen if I see it again.
