### ISSUE TITLE
Unable to load NODE with id while syncing snapshots for one of the AWS accounts

### ISSUE THREAD

**Issue by El070422** [lyft/cartography#840]
Hi everyone,

Please help me with the new issue. I have installed 0.57.0 version and after that cartography stopped collecting data for one the AWS accounts.

The error:
....
DEBUG:cartography.intel.aws.ec2.snapshots:Syncing snapshots for region '...' in account '...'.
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/util.py", line 117, in timed
    return method(*args, **kwargs)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 220, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 157, in _sync_multiple_accounts
    _sync_one_account(
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 60, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/util.py", line 117, in timed
    return method(*args, **kwargs)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/ec2/snapshots.py", line 142, in sync_ebs_snapshots
    load_snapshots(neo4j_session, data, region, current_aws_account_id, update_tag)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/util.py", line 117, in timed
    return method(*args, **kwargs)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/ec2/snapshots.py", line 76, in load_snapshots
    neo4j_session.run(
  File "/home/centos/.local/lib/python3.8/site-packages/neo4j/__init__.py", line 503, in run
    self._connection.fetch()
  File "/home/centos/.local/lib/python3.8/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/home/centos/.local/lib/python3.8/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/centos/.local/lib/python3.8/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: Unable to load NODE with id <>.

**Comment by ramonpetgrave64** [comment]
I'm assuming you did some redaction here?
```
...
neobolt.exceptions.ClientError: Unable to load NODE with id <>.
```

Can you help us debug this? Try putting some log statements, maybe printing out each of your snapshot dictionaries.

**Comment by marco-lancini** [comment]
> @marco-lancini I think you faced this before too?

*If* I remember correctly the one I faced was a different error 🤔

**Comment by El070422** [comment]
Hi @achantavy, yes, now I'm pretty sure that this is neo4j issue but I still don't know how it can be resolved. This is not related to memory issue bc neo4j is configured as it was recommended by memrec. And I can add other accounts. And this account works in test machine without issues. It's strange that the problematic node doesn't exist at all, so I can't remove it, as recommended on the forums. Removing and re-adding the account does not solve the problem either...

**Comment by El070422** [comment]
I have fixed the database, the issue is resolved.

**Comment by achantavy** [comment]
Glad to hear! How'd you fix it?
