### ISSUE TITLE
Unable to construct OffsetDateTime value: `Zone offset not in valid range: -18:00 to +18:00`

### ISSUE THREAD

**Issue by scornejob** [lyft/cartography#868]
Date handling not behaving correctly

*Description*:
> When running cartography, I'm having this stack:
```
ERROR:cartography.graph.job:Unhandled error while executing statement in job 'cleanup AWSLambda': Unable to construct OffsetDateTime value: `Zone offset not in valid range: -18:00 to +18:00`
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/sync.py", line 85, in run
    stage_func(neo4j_session, config)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 213, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 154, in _sync_multiple_accounts
    _sync_one_account(
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 60, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/lambda_function.py", line 259, in sync
    sync_lambda_functions(
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/lambda_function.py", line 251, in sync_lambda_functions
    cleanup_lambda(neo4j_session, common_job_parameters)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/lambda_function.py", line 236, in cleanup_lambda
    run_cleanup_job('aws_import_lambda_cleanup.json', neo4j_session, common_job_parameters)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 59, in run_cleanup_job
    GraphJob.run_from_json(
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/graph/job.py", line 114, in run_from_json
    job.run(neo4j_session)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/graph/job.py", line 58, in run
    stm.run(neo4j_session)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/graph/statement.py", line 68, in run
    self._run_iterative(session)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/graph/statement.py", line 115, in _run_iterative
    result: neo4j.StatementResult = session.write_transaction(self._run_noniterative)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neo4j/__init__.py", line 718, in write_transaction
    return self._run_transaction(WRITE_ACCESS, unit_of_work, *args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neo4j/__init__.py", line 679, in _run_transaction
    self._open_transaction(access_mode, metadata, timeout)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neo4j/__init__.py", line 619, in _open_transaction
    self._connect(access_mode)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neo4j/__init__.py", line 381, in _connect
    self._connection.sync()
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherTypeError: Unable to construct OffsetDateTime value: `Zone offset not in valid range: -18:00 to +18:00`
Traceback (most recent call last):
  File ".venv/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/cli.py", line 520, in main
    sys.exit(CLI(default_sync, prog='cartography').main(argv))
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/cli.py", line 500, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/sync.py", line 163, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/sync.py", line 85, in run
    stage_func(neo4j_session, config)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 213, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 154, in _sync_multiple_accounts
    _sync_one_account(
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 60, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/lambda_function.py", line 259, in sync
    sync_lambda_functions(
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/lambda_function.py", line 251, in sync_lambda_functions
    cleanup_lambda(neo4j_session, common_job_parameters)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/intel/aws/lambda_function.py", line 236, in cleanup_lambda
    run_cleanup_job('aws_import_lambda_cleanup.json', neo4j_session, common_job_parameters)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/util.py", line 59, in run_cleanup_job
    GraphJob.run_from_json(
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/graph/job.py", line 114, in run_from_json
    job.run(neo4j_session)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/graph/job.py", line 58, in run
    stm.run(neo4j_session)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/graph/statement.py", line 68, in run
    self._run_iterative(session)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/cartography/graph/statement.py", line 115, in _run_iterative
    result: neo4j.StatementResult = session.write_transaction(self._run_noniterative)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neo4j/__init__.py", line 718, in write_transaction
    return self._run_transaction(WRITE_ACCESS, unit_of_work, *args, **kwargs)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neo4j/__init__.py", line 679, in _run_transaction
    self._open_transaction(access_mode, metadata, timeout)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neo4j/__init__.py", line 619, in _open_transaction
    self._connect(access_mode)
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neo4j/__init__.py", line 381, in _connect
    self._connection.sync()
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/Users/scornejo/repo/cartography-python/.venv/lib/python3.8/site-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherTypeError: Unable to construct OffsetDateTime value: `Zone offset not in valid range: -18:00 to +18:00`
```
I found a similar report https://github.com/lyft/cartography/issues/649, so I implemented something similar for ECR https://github.com/lyft/cartography/compare/master...scornejob:date_issue

The problem is that now the same error appeared with AWS lambda functions, so I'm not sure if I missed something or effectively there's something going on with many dates.

*To Reproduce*:
> Well, I just run cartography, and get this results.

*Logs*:
> Se above :)

*Screenshots*:
> If applicable, add screenshots to help explain your problem.

*Please complete the following information:*:
>  - Cartography 0.62.0
>  - Python version: 3.8.10
>  - Monterey

**Comment by scornejob** [comment]
For lambda this happens on the clean-up job, and by looking at the nodes, I found `modifieddate` as:
`modifieddate: 2018-03-21T18:04:58.896+0000`. All other timestamps are unix epoch, so my problem might be around here. Do you agree?

**Comment by scornejob** [comment]
Noteworthy: (As stated on the previous issue) if I ran cartography setting the timezone to UTC, everything works:

`TZ=UTC cartography --yada --blah` works.

I don't think that for my use case is too bad to run in UTC FWIW.

**Comment by scornejob** [comment]
Closing to reduce noise.
