### ISSUE TITLE
KeyError exception when getting DNSName for load_balancer_id 

### ISSUE THREAD

**Issue by trodery** [lyft/cartography#996]
**Title**: `KeyError` exception when getting `DNSName` for `load_balancer_id`

**Description**: In the function `load_load_balancer_v2s` in `load_balancer_v2s.py` , a `KeyError` exception occurs when accessing the key `DNSName` from the dictionary representing an AWS load-balancer. It seems that `DNSName` is not a required field and, therefore, may not exist in the returned response from the AWS API.

**To Reproduce**:
The response dictionary that triggers this exception is below but has been obfuscated from the original by changing any unique identifiers.

```python
{   'AvailabilityZones': [   {   'SubnetId': 'subnet-096af4182d25d25e9',
                                 'ZoneName': 'us-west-2a'}],
    'CreatedTime': datetime.datetime(2021, 4, 25, 22, 39, 9, 433000, tzinfo=tzutc()),
    'Listeners': [   {   'DefaultActions': [   {   'ForwardConfig': {   'TargetGroups': [   {   'TargetGroupArn': 'arn:aws:elasticloadbalancing:us-west-2:779997416024:targetgroup/l3TestGwLbTg/00f3eb30a53b0003a9'}]},
                                                   'TargetGroupArn': 'arn:aws:elasticloadbalancing:us-west-2:779997416024:targetgroup/l3TestGwLbTg/00f3eb30a53b0003a9',
                                                   'Type': 'forward'}],
                         'ListenerArn': 'arn:aws:elasticloadbalancing:us-west-2:779997416024:listener/gwy/l3TestGWLB/ac9a04ffff55755f/1e2cee3afe7d7d69',
                         'LoadBalancerArn': 'arn:aws:elasticloadbalancing:us-west-2:779997416024:loadbalancer/gwy/l3TestGWLB/ac9a04ffff55755f'}],
    'LoadBalancerArn': 'arn:aws:elasticloadbalancing:us-west-2:779997416024:loadbalancer/gwy/l3TestGWLB/ac9a04ffff55755f',
    'LoadBalancerName': 'l3TestGWLB',
    'State': {'Code': 'active'},
    'TargetGroups': [   {   'HealthCheckEnabled': True,
                            'HealthCheckIntervalSeconds': 10,
                            'HealthCheckPort': '80',
                            'HealthCheckProtocol': 'TCP',
                            'HealthCheckTimeoutSeconds': 5,
                            'HealthyThresholdCount': 3,
                            'LoadBalancerArns': [   'arn:aws:elasticloadbalancing:us-west-2:779997416024:loadbalancer/gwy/l3TestGWLB/ac9a04ffff55755f'],
                            'Port': 6081,
                            'Protocol': 'GENEVE',
                            'TargetGroupArn': 'arn:aws:elasticloadbalancing:us-west-2:779997416024:targetgroup/l3TestGwLbTg/00f3eb30a53b0003a9',
                            'TargetGroupName': 'l3TestGwLbTg',
                            'TargetType': 'instance',
                            'Targets': ['i-0024ad3a48b431382'],
                            'UnhealthyThresholdCount': 3,
                            'VpcId': 'vpc-0c40bde5a351c8455'}],
    'Type': 'gateway',
    'VpcId': 'vpc-0c40bde5a351c8455'}
```

**Logs**:
The stack trace is below. While the stack trace is from `master` @ `57640510c5bb4939e7bcedf3690dec0236e6f331`, the problem persists at `HEAD` because the code in the function is the same.

```text
2022-09-22 13:47:54,693 ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/home/terryrodery/repos/misc_repos/cartography/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/home/terryrodery/repos/misc_repos/cartography/cartography/util.py", line 113, in timed
    return method(*args, **kwargs)
  File "/home/terryrodery/repos/misc_repos/cartography/cartography/intel/aws/__init__.py", line 239, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/home/terryrodery/repos/misc_repos/cartography/cartography/intel/aws/__init__.py", line 176, in _sync_multiple_accounts
    _sync_one_account(
  File "/home/terryrodery/repos/misc_repos/cartography/cartography/intel/aws/__init__.py", line 76, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/home/terryrodery/repos/misc_repos/cartography/cartography/util.py", line 113, in timed
    return method(*args, **kwargs)
  File "/home/terryrodery/repos/misc_repos/cartography/cartography/intel/aws/ec2/load_balancer_v2s.py", line 232, in sync_load_balancer_v2s
    load_load_balancer_v2s(neo4j_session, data, region, current_aws_account_id, update_tag)
  File "/home/terryrodery/repos/misc_repos/cartography/cartography/util.py", line 113, in timed
    return method(*args, **kwargs)
  File "/home/terryrodery/repos/misc_repos/cartography/cartography/intel/aws/ec2/load_balancer_v2s.py", line 80, in load_load_balancer_v2s
    load_balancer_id = lb["DNSName"]
KeyError: 'DNSName'
```

>  - Cartography release version or commit hash: `57640510c5bb4939e7bcedf3690dec0236e6f331` and `HEAD`
>  - Python version: 3.9.*
>  - OS (feel free to omit this if you don't think it's relevant to your issue): Ubuntu 20.04

**Additional Context**:

The offending code, including the function definition, is below. Depending on the preferred default value for a missing `DNSName` I believe this could be rectified by changing:

```python
load_balancer_id = lb["DNSName"]
```

to

```python
load_balancer_id = lb.get("DNSName", "")
```

Existing code for the function.

```python
@timeit
def load_load_balancer_v2s(
    neo4j_session: neo4j.Session, data: List[Dict], region: str, current_aws_account_id: str,
    update_tag: int,
) -> None:
    ingest_load_balancer_v2 = """
    MERGE (elbv2:LoadBalancerV2{id: $ID})
    ON CREATE SET elbv2.firstseen = timestamp(), elbv2.createdtime = $CREATED_TIME
    SET elbv2.lastupdated = $update_tag, elbv2.name = $NAME, elbv2.dnsname = $DNS_NAME,
    elbv2.canonicalhostedzonenameid = $HOSTED_ZONE_NAME_ID,
    elbv2.type = $ELBv2_TYPE,
    elbv2.scheme = $SCHEME, elbv2.region = $Region
    WITH elbv2
    MATCH (aa:AWSAccount{id: $AWS_ACCOUNT_ID})
    MERGE (aa)-[r:RESOURCE]->(elbv2)
    ON CREATE SET r.firstseen = timestamp()
    SET r.lastupdated = $update_tag
    """
    for lb in data:
        load_balancer_id = lb["DNSName"]
```

**Comment by trodery** [comment]
Let me know what the preferred default value for a `DNSName` is, and I will submit a PR with the fix. An empty string makes sense to me, but I am not familiar enough with the project yet to determine that.

**Comment by ramonpetgrave64** [comment]
Thanks for the find. The preferred way is to not set the node property, instead of supplying an empty string. So, you may open a PR to simply not set the dictionary's field, and Neo4j will still accept the query.

**Comment by aliahmed58** [comment]
This error only occurs when syncing load balancer of type `gateway` since it does not have the `DNSName` field. The `DNSName` field is used as `id` in neo4j when inserting `LoadBalancerV2` so skipping `DNSName` won't help, instead `arn` can be used as `load_balancer_id` then it won't result in a `KeyError`. Can I work on this fix and create a PR? (im fairly new to open source)

**Comment by ramonpetgrave64** [comment]
@aliahmed58 Yes, please feel free!
